In [ ]:
import sys
import os
import gc
import json
import time
import importlib
from pathlib import Path
from datetime import datetime
from collections import Counter

import numpy as np
import pandas as pd
import torch

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding,
    MarianMTModel,
    MarianTokenizer,
)

TARGET_PATH = "/content/drive/MyDrive/Thesis/models"

if TARGET_PATH not in sys.path:
    sys.path.insert(0, TARGET_PATH)

importlib.invalidate_caches()

from utils import DATA_DIR, MODELS_DIR, EKMAN_LABELS, set_all_seeds
from evaluate import compute_metrics

from train_phase3 import (
    GoEmotionsDataset,
    hf_compute_metrics,
    load_data,
    MODEL_NAME,
    MAX_LENGTH,
    BATCH_SIZE,
    N_EPOCHS,
    LEARNING_RATE,
    WEIGHT_DECAY,
    WARMUP_STEPS,
    NUM_LABELS,
)

OUTPUT_ROOT = Path(
    "/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs"
)

OUTPUT_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

SEEDS = [42, 0, 1]

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
def make_json_safe(value):
    if isinstance(value, dict):
        return {
            str(key): make_json_safe(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [
            make_json_safe(item)
            for item in value
        ]

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, np.generic):
        return value.item()

    return value


def get_selected_minority_classes(
    train_df,
    top_k=3,
):
    class_counts = (
        train_df["ekman_id"]
        .value_counts()
        .sort_values(ascending=True)
    )

    selected_class_ids = (
        class_counts
        .index[:top_k]
        .astype(int)
        .tolist()
    )

    return selected_class_ids, class_counts


def prepare_original_rows(train_df):
    train_df = train_df.copy()

    train_df["augmentation"] = "original"
    train_df["source_text"] = train_df["text_clean"]
    train_df["source_id"] = (
        train_df["id"]
        if "id" in train_df.columns
        else np.arange(len(train_df))
    )
    train_df["paraphrase_number"] = 0
    train_df["semantic_similarity"] = np.nan
    train_df["passed_similarity_filter"] = np.nan

    return train_df


def save_confusion_matrix_to_folder(
    y_true,
    y_pred,
    labels,
    output_path,
    title,
):
    matrix = confusion_matrix(
        y_true,
        y_pred,
        labels=list(range(len(labels))),
    )

    figure, axis = plt.subplots(
        figsize=(9, 8)
    )

    image = axis.imshow(
        matrix,
        interpolation="nearest",
        cmap="Blues",
    )

    figure.colorbar(
        image,
        ax=axis,
    )

    axis.set(
        xticks=np.arange(len(labels)),
        yticks=np.arange(len(labels)),
        xticklabels=labels,
        yticklabels=labels,
        xlabel="Predicted label",
        ylabel="True label",
        title=title,
    )

    plt.setp(
        axis.get_xticklabels(),
        rotation=45,
        ha="right",
        rotation_mode="anchor",
    )

    threshold = matrix.max() / 2 if matrix.size else 0

    for row_index in range(matrix.shape[0]):
        for column_index in range(matrix.shape[1]):
            axis.text(
                column_index,
                row_index,
                format(matrix[row_index, column_index], "d"),
                ha="center",
                va="center",
                color=(
                    "white"
                    if matrix[row_index, column_index] > threshold
                    else "black"
                ),
            )

    figure.tight_layout()

    figure.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(figure)

    return matrix

In [ ]:
def augment_direct_duplication(
    train_df,
    top_k=3,
    copies_per_source=3,
    seed=42,
):
    selected_class_ids, class_counts = get_selected_minority_classes(
        train_df,
        top_k=top_k,
    )

    selected_df = (
        train_df[
            train_df["ekman_id"].isin(selected_class_ids)
        ]
        .copy()
        .reset_index(drop=True)
    )

    extra_rows = []

    for row_index, row in selected_df.iterrows():
        source_id = (
            row["id"]
            if "id" in selected_df.columns
            else row_index
        )

        for copy_number in range(1, copies_per_source + 1):
            extra_rows.append({
                "text_clean": row["text_clean"],
                "ekman_id": int(row["ekman_id"]),
                "augmentation": "direct_duplication",
                "source_text": row["text_clean"],
                "source_id": source_id,
                "paraphrase_number": copy_number,
                "semantic_similarity": 1.0,
                "passed_similarity_filter": True,
            })

    extra_df = pd.DataFrame(extra_rows)

    augmented_df = pd.concat(
        [
            prepare_original_rows(train_df),
            extra_df,
        ],
        ignore_index=True,
    )

    augmented_counts = (
        augmented_df["ekman_id"]
        .value_counts()
        .sort_index()
    )

    report = {
        "method": "direct_duplication",
        "top_k": top_k,
        "copies_per_source": copies_per_source,
        "selected_class_ids": selected_class_ids,
        "original_training_size": int(len(train_df)),
        "selected_source_examples": int(len(selected_df)),
        "generated_synthetic_examples": int(len(extra_df)),
        "augmented_training_size": int(len(augmented_df)),
        "original_class_counts": {
            str(int(class_id)): int(count)
            for class_id, count
            in class_counts.sort_index().items()
        },
        "augmented_class_counts": {
            str(int(class_id)): int(count)
            for class_id, count
            in augmented_counts.items()
        },
    }

    return augmented_df, extra_df, report

In [ ]:
def augment_random_oversampling(
    train_df,
    top_k=3,
    oversample_factor=3,
    seed=42,
):
    rng = np.random.default_rng(seed)

    selected_class_ids, class_counts = get_selected_minority_classes(
        train_df,
        top_k=top_k,
    )

    extra_rows = []

    for class_id in selected_class_ids:
        class_df = (
            train_df[
                train_df["ekman_id"] == class_id
            ]
            .copy()
            .reset_index(drop=True)
        )

        n_to_add = len(class_df) * oversample_factor

        sampled_indices = rng.integers(
            low=0,
            high=len(class_df),
            size=n_to_add,
        )

        sampled_df = class_df.iloc[
            sampled_indices
        ].reset_index(drop=True)

        for sample_number, (_, row) in enumerate(
            sampled_df.iterrows(),
            start=1,
        ):
            source_id = (
                row["id"]
                if "id" in sampled_df.columns
                else sample_number
            )

            extra_rows.append({
                "text_clean": row["text_clean"],
                "ekman_id": int(row["ekman_id"]),
                "augmentation": "random_oversampling",
                "source_text": row["text_clean"],
                "source_id": source_id,
                "paraphrase_number": sample_number,
                "semantic_similarity": 1.0,
                "passed_similarity_filter": True,
            })

    extra_df = pd.DataFrame(extra_rows)

    augmented_df = pd.concat(
        [
            prepare_original_rows(train_df),
            extra_df,
        ],
        ignore_index=True,
    )

    augmented_counts = (
        augmented_df["ekman_id"]
        .value_counts()
        .sort_index()
    )

    report = {
        "method": "random_oversampling",
        "top_k": top_k,
        "oversample_factor": oversample_factor,
        "selected_class_ids": selected_class_ids,
        "original_training_size": int(len(train_df)),
        "generated_synthetic_examples": int(len(extra_df)),
        "augmented_training_size": int(len(augmented_df)),
        "original_class_counts": {
            str(int(class_id)): int(count)
            for class_id, count
            in class_counts.sort_index().items()
        },
        "augmented_class_counts": {
            str(int(class_id)): int(count)
            for class_id, count
            in augmented_counts.items()
        },
    }

    return augmented_df, extra_df, report

In [ ]:
def translate_deterministically(
    texts,
    tokenizer,
    model,
    device,
    batch_size=8,
    max_length=128,
):
    translations = []

    with torch.no_grad():
        for start in range(0, len(texts), batch_size):
            batch = texts[start:start + batch_size]

            encoded = tokenizer(
                batch,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=max_length,
            ).to(device)

            generated = model.generate(
                **encoded,
                max_length=max_length,
                num_beams=4,
                do_sample=False,
            )

            translations.extend(
                tokenizer.batch_decode(
                    generated,
                    skip_special_tokens=True,
                )
            )

    return translations


def generate_reverse_translation_candidates(
    pivot_texts,
    original_texts,
    tokenizer,
    model,
    device,
    candidates_per_source=12,
    batch_size=8,
    max_length=128,
    seed=42,
    maximum_attempts=8,
):
    """
    Generate a pool of distinct English back-translation candidates
    for each source example.
    """
    candidate_groups = []

    temperature_schedule = [
        0.80,
        0.90,
        1.00,
        1.10,
        1.20,
        1.30,
        1.40,
        1.50,
    ]

    top_p_schedule = [
        0.90,
        0.93,
        0.95,
        0.96,
        0.97,
        0.98,
        0.98,
        0.99,
    ]

    with torch.no_grad():
        for start in range(
            0,
            len(pivot_texts),
            batch_size,
        ):
            pivot_batch = pivot_texts[
                start:start + batch_size
            ]

            original_batch = original_texts[
                start:start + batch_size
            ]

            pools = [
                []
                for _ in pivot_batch
            ]

            for attempt in range(maximum_attempts):
                if all(
                    len(pool) >= candidates_per_source
                    for pool in pools
                ):
                    break

                current_seed = seed + start * 100 + attempt

                torch.manual_seed(current_seed)

                if torch.cuda.is_available():
                    torch.cuda.manual_seed_all(current_seed)

                temperature = temperature_schedule[
                    min(
                        attempt,
                        len(temperature_schedule) - 1,
                    )
                ]

                top_p = top_p_schedule[
                    min(
                        attempt,
                        len(top_p_schedule) - 1,
                    )
                ]

                encoded = tokenizer(
                    pivot_batch,
                    return_tensors="pt",
                    padding=True,
                    truncation=True,
                    max_length=max_length,
                ).to(device)

                generated = model.generate(
                    **encoded,
                    max_length=max_length,
                    do_sample=True,
                    num_beams=1,
                    top_p=top_p,
                    temperature=temperature,
                    num_return_sequences=candidates_per_source,
                )

                decoded = tokenizer.batch_decode(
                    generated,
                    skip_special_tokens=True,
                )

                for local_index, original_text in enumerate(
                    original_batch
                ):
                    start_index = (
                        local_index
                        * candidates_per_source
                    )

                    end_index = (
                        start_index
                        + candidates_per_source
                    )

                    raw_candidates = decoded[
                        start_index:end_index
                    ]

                    normalized_original = (
                        str(original_text)
                        .strip()
                        .lower()
                    )

                    for candidate in raw_candidates:
                        candidate = str(candidate).strip()

                        if not candidate:
                            continue

                        if candidate.lower() == normalized_original:
                            continue

                        if candidate not in pools[local_index]:
                            pools[local_index].append(candidate)

                        if len(pools[local_index]) >= candidates_per_source:
                            break

            candidate_groups.extend(pools)

    return candidate_groups


def create_backtranslation_candidate_pools(
    selected_df,
    pivot="de",
    candidates_per_source=12,
    batch_size=8,
    seed=42,
    maximum_attempts=8,
):
    source_texts = (
        selected_df["text_clean"]
        .astype(str)
        .tolist()
    )

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    forward_name = f"Helsinki-NLP/opus-mt-en-{pivot}"
    reverse_name = f"Helsinki-NLP/opus-mt-{pivot}-en"

    print(f"\nLoading {forward_name}...")

    forward_tokenizer = MarianTokenizer.from_pretrained(
        forward_name
    )

    forward_model = (
        MarianMTModel
        .from_pretrained(forward_name)
        .to(device)
        .eval()
    )

    print("\nTranslating English to pivot language...")

    pivot_texts = translate_deterministically(
        texts=source_texts,
        tokenizer=forward_tokenizer,
        model=forward_model,
        device=device,
        batch_size=batch_size,
    )

    del forward_model
    del forward_tokenizer
    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    print(f"\nLoading {reverse_name}...")

    reverse_tokenizer = MarianTokenizer.from_pretrained(
        reverse_name
    )

    reverse_model = (
        MarianMTModel
        .from_pretrained(reverse_name)
        .to(device)
        .eval()
    )

    print("\nGenerating English back-translation candidates...")

    candidate_groups = generate_reverse_translation_candidates(
        pivot_texts=pivot_texts,
        original_texts=source_texts,
        tokenizer=reverse_tokenizer,
        model=reverse_model,
        device=device,
        candidates_per_source=candidates_per_source,
        batch_size=batch_size,
        seed=seed,
        maximum_attempts=maximum_attempts,
    )

    del reverse_model
    del reverse_tokenizer
    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return source_texts, candidate_groups

In [ ]:
def augment_backtranslation_basic(
    train_df,
    top_k=3,
    aug_factor=1,
    candidates_per_source=12,
    maximum_attempts=8,
    pivot="de",
    batch_size=8,
    seed=42,
    method_name=None,
):
    if method_name is None:
        method_name = f"backtranslation_x{aug_factor}"

    selected_class_ids, class_counts = get_selected_minority_classes(
        train_df,
        top_k=top_k,
    )

    selected_df = (
        train_df[
            train_df["ekman_id"].isin(selected_class_ids)
        ]
        .copy()
        .reset_index(drop=True)
    )

    source_texts, candidate_groups = create_backtranslation_candidate_pools(
        selected_df=selected_df,
        pivot=pivot,
        candidates_per_source=candidates_per_source,
        batch_size=batch_size,
        seed=seed,
        maximum_attempts=maximum_attempts,
    )

    extra_rows = []

    for row_index, candidates in enumerate(candidate_groups):
        if len(candidates) < aug_factor:
            raise RuntimeError(
                f"Source row {row_index} produced only "
                f"{len(candidates)} candidates, but aug_factor="
                f"{aug_factor} was requested."
            )

        row = selected_df.iloc[row_index]

        source_id = (
            row["id"]
            if "id" in selected_df.columns
            else row_index
        )

        selected_candidates = candidates[:aug_factor]

        for paraphrase_number, paraphrase in enumerate(
            selected_candidates,
            start=1,
        ):
            extra_rows.append({
                "text_clean": paraphrase,
                "ekman_id": int(row["ekman_id"]),
                "augmentation": method_name,
                "source_text": source_texts[row_index],
                "source_id": source_id,
                "paraphrase_number": paraphrase_number,
                "semantic_similarity": np.nan,
                "passed_similarity_filter": np.nan,
            })

    extra_df = pd.DataFrame(extra_rows)

    augmented_df = pd.concat(
        [
            prepare_original_rows(train_df),
            extra_df,
        ],
        ignore_index=True,
    )

    augmented_counts = (
        augmented_df["ekman_id"]
        .value_counts()
        .sort_index()
    )

    report = {
        "method": method_name,
        "pivot_language": pivot,
        "top_k": top_k,
        "aug_factor": aug_factor,
        "candidates_per_source": candidates_per_source,
        "maximum_attempts": maximum_attempts,
        "selected_class_ids": selected_class_ids,
        "original_training_size": int(len(train_df)),
        "selected_source_examples": int(len(selected_df)),
        "generated_synthetic_examples": int(len(extra_df)),
        "augmented_training_size": int(len(augmented_df)),
        "original_class_counts": {
            str(int(class_id)): int(count)
            for class_id, count
            in class_counts.sort_index().items()
        },
        "augmented_class_counts": {
            str(int(class_id)): int(count)
            for class_id, count
            in augmented_counts.items()
        },
    }

    return augmented_df, extra_df, report

In [ ]:
def compute_pairwise_semantic_similarity(
    original_texts,
    candidate_texts,
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    batch_size=64,
):
    try:
        from sentence_transformers import SentenceTransformer
    except ImportError as error:
        raise ImportError(
            "sentence-transformers is required for semantic "
            "similarity filtering. Install it with:\n"
            "!pip install -q sentence-transformers"
        ) from error

    model = SentenceTransformer(model_name)

    original_embeddings = model.encode(
        original_texts,
        batch_size=batch_size,
        convert_to_numpy=True,
        normalize_embeddings=True,
        show_progress_bar=True,
    )

    candidate_embeddings = model.encode(
        candidate_texts,
        batch_size=batch_size,
        convert_to_numpy=True,
        normalize_embeddings=True,
        show_progress_bar=True,
    )

    similarities = np.sum(
        original_embeddings * candidate_embeddings,
        axis=1,
    )

    return similarities


def augment_backtranslation_similarity_filtered(
    train_df,
    top_k=3,
    aug_factor=3,
    candidates_per_source=12,
    maximum_attempts=8,
    pivot="de",
    batch_size=8,
    seed=42,
    min_similarity=0.75,
    max_similarity=0.98,
    fallback_to_best=True,
    similarity_model_name="sentence-transformers/all-MiniLM-L6-v2",
):

    selected_class_ids, class_counts = get_selected_minority_classes(
        train_df,
        top_k=top_k,
    )

    selected_df = (
        train_df[
            train_df["ekman_id"].isin(selected_class_ids)
        ]
        .copy()
        .reset_index(drop=True)
    )

    source_texts, candidate_groups = create_backtranslation_candidate_pools(
        selected_df=selected_df,
        pivot=pivot,
        candidates_per_source=candidates_per_source,
        batch_size=batch_size,
        seed=seed,
        maximum_attempts=maximum_attempts,
    )

    flat_originals = []
    flat_candidates = []
    flat_source_indices = []

    for source_index, candidates in enumerate(candidate_groups):
        for candidate in candidates:
            flat_originals.append(source_texts[source_index])
            flat_candidates.append(candidate)
            flat_source_indices.append(source_index)

    if len(flat_candidates) == 0:
        raise RuntimeError(
            "No back-translation candidates were generated."
        )

    print("\nComputing semantic similarities...")

    similarities = compute_pairwise_semantic_similarity(
        original_texts=flat_originals,
        candidate_texts=flat_candidates,
        model_name=similarity_model_name,
    )

    candidates_by_source = {
        source_index: []
        for source_index in range(len(source_texts))
    }

    for candidate, source_index, similarity in zip(
        flat_candidates,
        flat_source_indices,
        similarities,
    ):
        passed_filter = (
            similarity >= min_similarity
            and similarity <= max_similarity
        )

        candidates_by_source[source_index].append({
            "text": candidate,
            "similarity": float(similarity),
            "passed_filter": bool(passed_filter),
        })

    extra_rows = []
    insufficient_sources = 0

    for source_index in range(len(source_texts)):
        row = selected_df.iloc[source_index]

        source_id = (
            row["id"]
            if "id" in selected_df.columns
            else source_index
        )

        candidates = candidates_by_source[source_index]

        passing_candidates = [
            candidate
            for candidate in candidates
            if candidate["passed_filter"]
        ]

        passing_candidates = sorted(
            passing_candidates,
            key=lambda item: item["similarity"],
            reverse=True,
        )

        chosen = passing_candidates[:aug_factor]

        if len(chosen) < aug_factor:
            insufficient_sources += 1

            if fallback_to_best:
                already_chosen_texts = {
                    item["text"]
                    for item in chosen
                }

                remaining_candidates = [
                    candidate
                    for candidate in candidates
                    if candidate["text"] not in already_chosen_texts
                ]

                remaining_candidates = sorted(
                    remaining_candidates,
                    key=lambda item: item["similarity"],
                    reverse=True,
                )

                needed = aug_factor - len(chosen)

                chosen.extend(
                    remaining_candidates[:needed]
                )

        for paraphrase_number, candidate in enumerate(
            chosen,
            start=1,
        ):
            extra_rows.append({
                "text_clean": candidate["text"],
                "ekman_id": int(row["ekman_id"]),
                "augmentation": "backtranslation_similarity_filtered",
                "source_text": source_texts[source_index],
                "source_id": source_id,
                "paraphrase_number": paraphrase_number,
                "semantic_similarity": candidate["similarity"],
                "passed_similarity_filter": candidate["passed_filter"],
            })

    extra_df = pd.DataFrame(extra_rows)

    augmented_df = pd.concat(
        [
            prepare_original_rows(train_df),
            extra_df,
        ],
        ignore_index=True,
    )

    augmented_counts = (
        augmented_df["ekman_id"]
        .value_counts()
        .sort_index()
    )

    if len(extra_df) > 0:
        mean_similarity = float(
            extra_df["semantic_similarity"].mean()
        )

        passed_count = int(
            extra_df["passed_similarity_filter"]
            .fillna(False)
            .sum()
        )
    else:
        mean_similarity = None
        passed_count = 0

    report = {
        "method": "backtranslation_similarity_filtered",
        "pivot_language": pivot,
        "top_k": top_k,
        "aug_factor": aug_factor,
        "candidates_per_source": candidates_per_source,
        "maximum_attempts": maximum_attempts,
        "min_similarity": min_similarity,
        "max_similarity": max_similarity,
        "fallback_to_best": fallback_to_best,
        "similarity_model_name": similarity_model_name,
        "selected_class_ids": selected_class_ids,
        "original_training_size": int(len(train_df)),
        "selected_source_examples": int(len(selected_df)),
        "generated_synthetic_examples": int(len(extra_df)),
        "sources_with_insufficient_passing_candidates": int(insufficient_sources),
        "passed_similarity_filter_count": passed_count,
        "mean_semantic_similarity": mean_similarity,
        "augmented_training_size": int(len(augmented_df)),
        "original_class_counts": {
            str(int(class_id)): int(count)
            for class_id, count
            in class_counts.sort_index().items()
        },
        "augmented_class_counts": {
            str(int(class_id)): int(count)
            for class_id, count
            in augmented_counts.items()
        },
    }

    return augmented_df, extra_df, report

In [ ]:
def apply_augmentation_control(
    train_df,
    control_name,
    seed=42,
    top_k=3,
):
    if control_name == "direct_duplication_x3":
        return augment_direct_duplication(
            train_df=train_df,
            top_k=top_k,
            copies_per_source=3,
            seed=seed,
        )

    if control_name == "random_oversampling_x3":
        return augment_random_oversampling(
            train_df=train_df,
            top_k=top_k,
            oversample_factor=3,
            seed=seed,
        )

    if control_name == "bt_single_x1":
        return augment_backtranslation_basic(
            train_df=train_df,
            top_k=top_k,
            aug_factor=1,
            candidates_per_source=8,
            maximum_attempts=8,
            pivot="de",
            batch_size=8,
            seed=seed,
            method_name="backtranslation_single_x1",
        )

    if control_name == "bt_diverse_x2":
        return augment_backtranslation_basic(
            train_df=train_df,
            top_k=top_k,
            aug_factor=2,
            candidates_per_source=10,
            maximum_attempts=8,
            pivot="de",
            batch_size=8,
            seed=seed,
            method_name="backtranslation_diverse_x2",
        )

    if control_name == "bt_diverse_x3":
        return augment_backtranslation_basic(
            train_df=train_df,
            top_k=top_k,
            aug_factor=3,
            candidates_per_source=12,
            maximum_attempts=8,
            pivot="de",
            batch_size=8,
            seed=seed,
            method_name="backtranslation_diverse_x3",
        )

    if control_name == "bt_similarity_filtered_x3":
        return augment_backtranslation_similarity_filtered(
            train_df=train_df,
            top_k=top_k,
            aug_factor=3,
            candidates_per_source=12,
            maximum_attempts=8,
            pivot="de",
            batch_size=8,
            seed=seed,
            min_similarity=0.75,
            max_similarity=0.98,
            fallback_to_best=True,
        )

    raise ValueError(
        f"Unknown control_name: {control_name}"
    )

In [ ]:
def run_bt_control_experiment(
    control_name,
    seed=42,
    top_k=3,
    output_root=OUTPUT_ROOT,
):
    set_all_seeds(seed)

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    run_name = (
        f"phase4_control_{control_name}_"
        f"seed{seed}_{timestamp}"
    )

    out_dir = Path(output_root) / run_name

    if out_dir.exists():
        raise FileExistsError(
            f"Output folder already exists:\n{out_dir}"
        )

    out_dir.mkdir(
        parents=True,
        exist_ok=False,
    )

    print("=" * 80)
    print("PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT")
    print("=" * 80)
    print(f"Control: {control_name}")
    print(f"Seed:    {seed}")
    print(f"Output:  {out_dir}")
    print("=" * 80)

    train_df, val_df, test_df = load_data()

    original_training_size = len(train_df)

    original_class_counts = (
        train_df["ekman_id"]
        .value_counts()
        .sort_index()
        .to_dict()
    )

    print("\nOriginal dataset sizes:")
    print(f"Training:   {len(train_df):,}")
    print(f"Validation: {len(val_df):,}")
    print(f"Test:       {len(test_df):,}")

    print("\nOriginal training class counts:")
    print(
        train_df["ekman_id"]
        .value_counts()
        .sort_index()
        .to_string()
    )

    augmentation_start = time.time()

    train_df, synthetic_df, augmentation_report = apply_augmentation_control(
        train_df=train_df,
        control_name=control_name,
        seed=seed,
        top_k=top_k,
    )

    augmentation_time = time.time() - augmentation_start

    print(
        f"\nAugmentation completed in "
        f"{augmentation_time:.1f} seconds "
        f"({augmentation_time / 60:.2f} minutes)."
    )

    print("\nFinal training class counts:")
    print(
        train_df["ekman_id"]
        .value_counts()
        .sort_index()
        .to_string()
    )

    synthetic_df.to_csv(
        out_dir / "generated_synthetic_examples.csv",
        index=False,
    )

    with open(
        out_dir / "augmentation_report.json",
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            make_json_safe(augmentation_report),
            file,
            indent=2,
            ensure_ascii=False,
        )


    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME
    )

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=NUM_LABELS,
        id2label={
            index: label
            for index, label in enumerate(EKMAN_LABELS)
        },
        label2id={
            label: index
            for index, label in enumerate(EKMAN_LABELS)
        },
    )

    train_ds = GoEmotionsDataset(
        train_df["text_clean"],
        train_df["ekman_id"],
        tokenizer,
    )

    val_ds = GoEmotionsDataset(
        val_df["text_clean"],
        val_df["ekman_id"],
        tokenizer,
    )

    test_ds = GoEmotionsDataset(
        test_df["text_clean"],
        test_df["ekman_id"],
        tokenizer,
    )

    training_args = TrainingArguments(
        output_dir=str(out_dir / "checkpoints"),
        learning_rate=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        num_train_epochs=N_EPOCHS,
        warmup_steps=WARMUP_STEPS,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="macro_f1",
        greater_is_better=True,
        save_total_limit=2,
        logging_steps=100,
        seed=seed,
        data_seed=seed,
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        processing_class=tokenizer,
        data_collator=DataCollatorWithPadding(
            tokenizer=tokenizer
        ),
        compute_metrics=hf_compute_metrics,
    )

    print("\nStarting training...")

    training_start = time.time()

    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()

    train_result = trainer.train()

    training_time = time.time() - training_start

    peak_gpu_memory_gb = None

    if torch.cuda.is_available():
        peak_gpu_memory_gb = (
            torch.cuda.max_memory_allocated() / 1e9
        )

    print(
        f"\nTraining completed in "
        f"{training_time:.1f} seconds "
        f"({training_time / 60:.2f} minutes)."
    )

    if peak_gpu_memory_gb is not None:
        print(
            f"Peak GPU memory: "
            f"{peak_gpu_memory_gb:.2f} GB"
        )

    best_model_dir = out_dir / "best_model"

    trainer.save_model(
        str(best_model_dir)
    )

    tokenizer.save_pretrained(
        str(best_model_dir)
    )


    def evaluate_and_save(
        dataset,
        dataframe,
        split_name,
    ):
        print(f"\nEvaluating {split_name} set...")

        prediction_output = trainer.predict(
            dataset,
            metric_key_prefix=split_name,
        )

        logits = prediction_output.predictions

        if isinstance(logits, tuple):
            logits = logits[0]

        y_true = prediction_output.label_ids.astype(int)
        y_pred = np.argmax(
            logits,
            axis=-1,
        ).astype(int)

        stable_logits = (
            logits
            - np.max(
                logits,
                axis=1,
                keepdims=True,
            )
        )

        exponentials = np.exp(stable_logits)

        probabilities = (
            exponentials
            / np.sum(
                exponentials,
                axis=1,
                keepdims=True,
            )
        )

        split_metrics = compute_metrics(
            y_true,
            y_pred,
            EKMAN_LABELS,
        )

        prediction_columns = {
            "text_clean": dataframe["text_clean"]
                .astype(str)
                .tolist(),
            "true_id": y_true,
            "true_label": [
                EKMAN_LABELS[value]
                for value in y_true
            ],
            "predicted_id": y_pred,
            "predicted_label": [
                EKMAN_LABELS[value]
                for value in y_pred
            ],
            "correct": y_true == y_pred,
        }

        if "id" in dataframe.columns:
            prediction_columns = {
                "id": dataframe["id"].tolist(),
                **prediction_columns,
            }

        predictions_dataframe = pd.DataFrame(
            prediction_columns
        )

        for class_index, class_name in enumerate(EKMAN_LABELS):
            safe_class_name = (
                str(class_name)
                .lower()
                .replace(" ", "_")
            )

            predictions_dataframe[
                f"probability_{safe_class_name}"
            ] = probabilities[:, class_index]

        predictions_dataframe.to_csv(
            out_dir / f"{split_name}_predictions.csv",
            index=False,
        )

        matrix = save_confusion_matrix_to_folder(
            y_true=y_true,
            y_pred=y_pred,
            labels=EKMAN_LABELS,
            output_path=(
                out_dir
                / f"{split_name}_confusion_matrix.png"
            ),
            title=f"{split_name.capitalize()} confusion matrix",
        )

        np.savetxt(
            out_dir / f"{split_name}_confusion_matrix.csv",
            matrix,
            delimiter=",",
            fmt="%d",
        )

        with open(
            out_dir / f"{split_name}_metrics.json",
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                make_json_safe(split_metrics),
                file,
                indent=2,
                ensure_ascii=False,
            )

        return split_metrics

    validation_metrics = evaluate_and_save(
        dataset=val_ds,
        dataframe=val_df,
        split_name="validation",
    )

    test_metrics = evaluate_and_save(
        dataset=test_ds,
        dataframe=test_df,
        split_name="test",
    )

    final_class_counts = (
        train_df["ekman_id"]
        .value_counts()
        .sort_index()
        .to_dict()
    )

    complete_results = {
        "run_name": run_name,
        "control_name": control_name,
        "seed": seed,
        "model_name": MODEL_NAME,
        "top_k": top_k,
        "original_training_size": int(original_training_size),
        "final_training_size": int(len(train_df)),
        "generated_synthetic_examples": int(len(synthetic_df)),
        "original_training_class_counts": {
            str(int(key)): int(value)
            for key, value in original_class_counts.items()
        },
        "final_training_class_counts": {
            str(int(key)): int(value)
            for key, value in final_class_counts.items()
        },
        "augmentation_time_seconds": augmentation_time,
        "training_time_seconds": training_time,
        "peak_gpu_memory_gb": peak_gpu_memory_gb,
        "best_checkpoint": trainer.state.best_model_checkpoint,
        "best_validation_macro_f1_during_training": trainer.state.best_metric,
        "augmentation": augmentation_report,
        "validation": validation_metrics,
        "test": test_metrics,
    }

    with open(
        out_dir / "complete_results.json",
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            make_json_safe(complete_results),
            file,
            indent=2,
            ensure_ascii=False,
        )

    with open(
        out_dir / "training_log_history.json",
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            make_json_safe(trainer.state.log_history),
            file,
            indent=2,
            ensure_ascii=False,
        )

    print("\n" + "=" * 80)
    print("FINAL RESULTS")
    print("=" * 80)

    print("\nValidation metrics:")
    print(
        json.dumps(
            make_json_safe(validation_metrics),
            indent=2,
        )
    )

    print("\nTest metrics:")
    print(
        json.dumps(
            make_json_safe(test_metrics),
            indent=2,
        )
    )

    print("\nAll results saved in:")
    print(out_dir)

    print("=" * 80)

    return complete_results

In [ ]:
CONTROL_EXPERIMENTS = [
    "direct_duplication_x3",

    "random_oversampling_x3",

    "bt_single_x1",

    "bt_diverse_x2",

    "bt_similarity_filtered_x3",
]

In [ ]:
def run_one_control_for_all_seeds(
    control_name,
    seeds=SEEDS,
    top_k=3,
    output_root=OUTPUT_ROOT,
):
    results = []

    print("=" * 80)
    print(f"Running control experiment: {control_name}")
    print(f"Seeds: {seeds}")
    print("=" * 80)

    for seed in seeds:
        print("\n" + "-" * 80)
        print(f"Starting {control_name} with seed {seed}")
        print("-" * 80)

        result = run_bt_control_experiment(
            control_name=control_name,
            seed=seed,
            top_k=top_k,
            output_root=output_root,
        )

        results.append(result)

        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    print("\n" + "=" * 80)
    print(f"Finished control experiment: {control_name}")
    print("=" * 80)

    return results

In [ ]:
direct_duplication_results = run_one_control_for_all_seeds(
    control_name="direct_duplication_x3",
)

================================================================================
Running control experiment: direct_duplication_x3
Seeds: [42, 0, 1]
================================================================================

--------------------------------------------------------------------------------
Starting direct_duplication_x3 with seed 42
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: direct_duplication_x3
Seed:    42
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_direct_duplication_x3_seed42_20260701_155647
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Augmentation completed in 0.3 seconds (0.01 minutes).

Final training class counts:
ekman_id
0     3878
1     1988
2     2060
3    12920
4     8484
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 518.1 seconds (8.64 minutes).
Peak GPU memory: 3.29 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6910050582801848,
  "macro_f1": 0.6095455919116967,
  "weighted_f1": 0.6916945101464693,
  "per_class_f1": [
    0.5155746509129968,
    0.46153846153846156,
    0.6056338028169014,
    0.8149262714414686,
    0.6123188405797102,
    0.5878220140515222,
    0.6690051020408163
  ],
  "report": {
    "anger": {
      "precision": 0.5381165919282511,
      "recall": 0.4948453608247423,
      "f1-score": 0.5155746509129968,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.37894736842105264,
      "recall": 0.5901639344262295,
      "f1-score": 0.46153846153846156,
      "support": 61.0
    },
    "fear": {
      "precision": 0.5657894736842105,
      "recall": 0.6515151515151515,
      "f1-score": 0.6056338028169014,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8181268882175227,
      "recall": 0.8117505995203836,
      "f1-score": 0.8149262714414686,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5434083601286174,
      "recall": 0.7012448132780082,
      "f1-score": 0.6123188405797102,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5990453460620525,
      "recall": 0.5770114942528736,
      "f1-score": 0.5878220140515222,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6789644012944984,
      "recall": 0.6593337523570082,
      "f1-score": 0.6690051020408163,
      "support": 1591.0
    },
    "accuracy": 0.6910050582801848,
    "macro avg": {
      "precision": 0.5889140613908864,
      "recall": 0.6408378723106282,
      "f1-score": 0.6095455919116967,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6944927631749304,
      "recall": 0.6910050582801848,
      "f1-score": 0.6916945101464693,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6849673202614379,
  "macro_f1": 0.6122135135605227,
  "weighted_f1": 0.6845363220982328,
  "per_class_f1": [
    0.5308641975308642,
    0.49162011173184356,
    0.6363636363636364,
    0.8132678132678133,
    0.5689948892674617,
    0.5790055248618785,
    0.665378421900161
  ],
  "report": {
    "anger": {
      "precision": 0.5707964601769911,
      "recall": 0.49615384615384617,
      "f1-score": 0.5308641975308642,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.42718446601941745,
      "recall": 0.5789473684210527,
      "f1-score": 0.49162011173184356,
      "support": 76.0
    },
    "fear": {
      "precision": 0.5656565656565656,
      "recall": 0.7272727272727273,
      "f1-score": 0.6363636363636364,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8009679370840895,
      "recall": 0.825951341235184,
      "f1-score": 0.8132678132678133,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5091463414634146,
      "recall": 0.6447876447876448,
      "f1-score": 0.5689948892674617,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5745614035087719,
      "recall": 0.5835189309576837,
      "f1-score": 0.5790055248618785,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6891260840560374,
      "recall": 0.6432129514321295,
      "f1-score": 0.665378421900161,
      "support": 1606.0
    },
    "accuracy": 0.6849673202614379,
    "macro avg": {
      "precision": 0.5910627511378983,
      "recall": 0.6428349728943239,
      "f1-score": 0.6122135135605227,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6870088891109633,
      "recall": 0.6849673202614379,
      "f1-score": 0.6845363220982328,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_direct_duplication_x3_seed42_20260701_155647
================================================================================

--------------------------------------------------------------------------------
Starting direct_duplication_x3 with seed 0
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: direct_duplication_x3
Seed:    0
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_direct_duplication_x3_seed0_20260701_160542
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Augmentation completed in 0.4 seconds (0.01 minutes).

Final training class counts:
ekman_id
0     3878
1     1988
2     2060
3    12920
4     8484
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 515.9 seconds (8.60 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6857268528700242,
  "macro_f1": 0.6124402681396132,
  "weighted_f1": 0.6862898050498659,
  "per_class_f1": [
    0.46941323345817726,
    0.48322147651006714,
    0.6708860759493671,
    0.8065429380308273,
    0.5985663082437276,
    0.5818561001042752,
    0.676595744680851
  ],
  "report": {
    "anger": {
      "precision": 0.5949367088607594,
      "recall": 0.38762886597938145,
      "f1-score": 0.46941323345817726,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.4090909090909091,
      "recall": 0.5901639344262295,
      "f1-score": 0.48322147651006714,
      "support": 61.0
    },
    "fear": {
      "precision": 0.5760869565217391,
      "recall": 0.803030303030303,
      "f1-score": 0.6708860759493671,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8484447385837194,
      "recall": 0.7685851318944844,
      "f1-score": 0.8065429380308273,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.526813880126183,
      "recall": 0.6929460580912863,
      "f1-score": 0.5985663082437276,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5324427480916031,
      "recall": 0.6413793103448275,
      "f1-score": 0.5818561001042752,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6550912301353737,
      "recall": 0.6995600251414205,
      "f1-score": 0.676595744680851,
      "support": 1591.0
    },
    "accuracy": 0.6857268528700242,
    "macro avg": {
      "precision": 0.591843881630041,
      "recall": 0.6547562327011333,
      "f1-score": 0.6124402681396132,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6966244336960039,
      "recall": 0.6857268528700242,
      "f1-score": 0.6862898050498659,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6760348583877995,
  "macro_f1": 0.6181824065679706,
  "weighted_f1": 0.6751868372488508,
  "per_class_f1": [
    0.45390070921985815,
    0.56,
    0.6878306878306878,
    0.8002589834898025,
    0.5858585858585859,
    0.5682951146560319,
    0.6711327649208283
  ],
  "report": {
    "anger": {
      "precision": 0.588957055214724,
      "recall": 0.36923076923076925,
      "f1-score": 0.45390070921985815,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.494949494949495,
      "recall": 0.6447368421052632,
      "f1-score": 0.56,
      "support": 76.0
    },
    "fear": {
      "precision": 0.5803571428571429,
      "recall": 0.8441558441558441,
      "f1-score": 0.6878306878306878,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8317631224764468,
      "recall": 0.7710542732376794,
      "f1-score": 0.8002589834898025,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5194029850746269,
      "recall": 0.6718146718146718,
      "f1-score": 0.5858585858585859,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5144404332129964,
      "recall": 0.6347438752783965,
      "f1-score": 0.5682951146560319,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6567342073897497,
      "recall": 0.6861768368617683,
      "f1-score": 0.6711327649208283,
      "support": 1606.0
    },
    "accuracy": 0.6760348583877995,
    "macro avg": {
      "precision": 0.5980863487393117,
      "recall": 0.6602733018120561,
      "f1-score": 0.6181824065679706,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6845537865735216,
      "recall": 0.6760348583877995,
      "f1-score": 0.6751868372488508,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_direct_duplication_x3_seed0_20260701_160542
================================================================================

--------------------------------------------------------------------------------
Starting direct_duplication_x3 with seed 1
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: direct_duplication_x3
Seed:    1
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_direct_duplication_x3_seed1_20260701_161439
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Augmentation completed in 0.3 seconds (0.00 minutes).

Final training class counts:
ekman_id
0     3878
1     1988
2     2060
3    12920
4     8484
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 512.0 seconds (8.53 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6885858808005278,
  "macro_f1": 0.5997594104378342,
  "weighted_f1": 0.6894690641186463,
  "per_class_f1": [
    0.5155746509129968,
    0.43137254901960786,
    0.5874125874125874,
    0.8161676646706587,
    0.5950704225352113,
    0.586483390607102,
    0.6662346079066753
  ],
  "report": {
    "anger": {
      "precision": 0.5381165919282511,
      "recall": 0.4948453608247423,
      "f1-score": 0.5155746509129968,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.358695652173913,
      "recall": 0.5409836065573771,
      "f1-score": 0.43137254901960786,
      "support": 61.0
    },
    "fear": {
      "precision": 0.5454545454545454,
      "recall": 0.6363636363636364,
      "f1-score": 0.5874125874125874,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8151913875598086,
      "recall": 0.8171462829736211,
      "f1-score": 0.8161676646706587,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5168195718654435,
      "recall": 0.7012448132780082,
      "f1-score": 0.5950704225352113,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5844748858447488,
      "recall": 0.5885057471264368,
      "f1-score": 0.586483390607102,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6876254180602007,
      "recall": 0.6461345065996229,
      "f1-score": 0.6662346079066753,
      "support": 1591.0
    },
    "accuracy": 0.6885858808005278,
    "macro avg": {
      "precision": 0.5780540075552729,
      "recall": 0.6321748505319206,
      "f1-score": 0.5997594104378342,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6930763907220998,
      "recall": 0.6885858808005278,
      "f1-score": 0.6894690641186463,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6843137254901961,
  "macro_f1": 0.6118802059044673,
  "weighted_f1": 0.6835187288033139,
  "per_class_f1": [
    0.5141129032258065,
    0.48554913294797686,
    0.6480446927374302,
    0.8163764130766881,
    0.5830508474576271,
    0.5717463848720801,
    0.664281067013663
  ],
  "report": {
    "anger": {
      "precision": 0.5402542372881356,
      "recall": 0.49038461538461536,
      "f1-score": 0.5141129032258065,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.4329896907216495,
      "recall": 0.5526315789473685,
      "f1-score": 0.48554913294797686,
      "support": 76.0
    },
    "fear": {
      "precision": 0.5686274509803921,
      "recall": 0.7532467532467533,
      "f1-score": 0.6480446927374302,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8,
      "recall": 0.8334373050530256,
      "f1-score": 0.8163764130766881,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5196374622356495,
      "recall": 0.6640926640926641,
      "f1-score": 0.5830508474576271,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5711111111111111,
      "recall": 0.5723830734966593,
      "f1-score": 0.5717463848720801,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6955040871934605,
      "recall": 0.6357409713574097,
      "f1-score": 0.664281067013663,
      "support": 1606.0
    },
    "accuracy": 0.6843137254901961,
    "macro avg": {
      "precision": 0.5897320056471997,
      "recall": 0.6431309945112137,
      "f1-score": 0.6118802059044673,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6858427645426549,
      "recall": 0.6843137254901961,
      "f1-score": 0.6835187288033139,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_direct_duplication_x3_seed1_20260701_161439
================================================================================

================================================================================
Finished control experiment: direct_duplication_x3
================================================================================

In [ ]:
random_oversampling_results = run_one_control_for_all_seeds(
    control_name="random_oversampling_x3",
)

================================================================================
Running control experiment: random_oversampling_x3
Seeds: [42, 0, 1]
================================================================================

--------------------------------------------------------------------------------
Starting random_oversampling_x3 with seed 42
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: random_oversampling_x3
Seed:    42
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_random_oversampling_x3_seed42_20260701_162330
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Augmentation completed in 0.8 seconds (0.01 minutes).

Final training class counts:
ekman_id
0     3878
1     1988
2     2060
3    12920
4     8484
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 506.3 seconds (8.44 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6956234880140753,
  "macro_f1": 0.6194061809047561,
  "weighted_f1": 0.6959852450844588,
  "per_class_f1": [
    0.5375661375661376,
    0.4533333333333333,
    0.6617647058823529,
    0.8198386614878996,
    0.6125461254612546,
    0.5817757009345794,
    0.6690186016677357
  ],
  "report": {
    "anger": {
      "precision": 0.5521739130434783,
      "recall": 0.5237113402061856,
      "f1-score": 0.5375661375661376,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.38202247191011235,
      "recall": 0.5573770491803278,
      "f1-score": 0.4533333333333333,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6428571428571429,
      "recall": 0.6818181818181818,
      "f1-score": 0.6617647058823529,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8171530673019655,
      "recall": 0.8225419664268585,
      "f1-score": 0.8198386614878996,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5514950166112956,
      "recall": 0.6887966804979253,
      "f1-score": 0.6125461254612546,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5914489311163895,
      "recall": 0.5724137931034483,
      "f1-score": 0.5817757009345794,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6830386378519974,
      "recall": 0.6555625392834695,
      "f1-score": 0.6690186016677357,
      "support": 1591.0
    },
    "accuracy": 0.6956234880140753,
    "macro avg": {
      "precision": 0.6028841686703402,
      "recall": 0.6431745072166282,
      "f1-score": 0.6194061809047561,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6979222923163257,
      "recall": 0.6956234880140753,
      "f1-score": 0.6959852450844588,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6856209150326797,
  "macro_f1": 0.6162397518480169,
  "weighted_f1": 0.6850686278245295,
  "per_class_f1": [
    0.5100806451612904,
    0.5121951219512195,
    0.6627906976744186,
    0.8168667282240689,
    0.5616438356164384,
    0.5819397993311036,
    0.6681614349775785
  ],
  "report": {
    "anger": {
      "precision": 0.5360169491525424,
      "recall": 0.48653846153846153,
      "f1-score": 0.5100806451612904,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.4772727272727273,
      "recall": 0.5526315789473685,
      "f1-score": 0.5121951219512195,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6,
      "recall": 0.7402597402597403,
      "f1-score": 0.6627906976744186,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8061968408262454,
      "recall": 0.8278228321896444,
      "f1-score": 0.8168667282240689,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5046153846153846,
      "recall": 0.6332046332046332,
      "f1-score": 0.5616438356164384,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5825892857142857,
      "recall": 0.5812917594654788,
      "f1-score": 0.5819397993311036,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6879947229551451,
      "recall": 0.6494396014943961,
      "f1-score": 0.6681614349775785,
      "support": 1606.0
    },
    "accuracy": 0.6856209150326797,
    "macro avg": {
      "precision": 0.5992408443623329,
      "recall": 0.6387412295856746,
      "f1-score": 0.6162397518480169,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6864341123406498,
      "recall": 0.6856209150326797,
      "f1-score": 0.6850686278245295,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_random_oversampling_x3_seed42_20260701_162330
================================================================================

--------------------------------------------------------------------------------
Starting random_oversampling_x3 with seed 0
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: random_oversampling_x3
Seed:    0
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_random_oversampling_x3_seed0_20260701_163217
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Augmentation completed in 0.6 seconds (0.01 minutes).

Final training class counts:
ekman_id
0     3878
1     1988
2     2060
3    12920
4     8484
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 501.7 seconds (8.36 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6927644600835716,
  "macro_f1": 0.6183365673701837,
  "weighted_f1": 0.6924400502179169,
  "per_class_f1": [
    0.4628930817610063,
    0.4457831325301205,
    0.7083333333333334,
    0.8191653786707882,
    0.6305970149253731,
    0.5842931937172775,
    0.6772908366533864
  ],
  "report": {
    "anger": {
      "precision": 0.5935483870967742,
      "recall": 0.37938144329896906,
      "f1-score": 0.4628930817610063,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.3523809523809524,
      "recall": 0.6065573770491803,
      "f1-score": 0.4457831325301205,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6538461538461539,
      "recall": 0.7727272727272727,
      "f1-score": 0.7083333333333334,
      "support": 66.0
    },
    "joy": {
      "precision": 0.845564773452457,
      "recall": 0.7943645083932853,
      "f1-score": 0.8191653786707882,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5728813559322034,
      "recall": 0.7012448132780082,
      "f1-score": 0.6305970149253731,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5365384615384615,
      "recall": 0.6413793103448275,
      "f1-score": 0.5842931937172775,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6608851674641149,
      "recall": 0.6945317410433689,
      "f1-score": 0.6772908366533864,
      "support": 1591.0
    },
    "accuracy": 0.6927644600835716,
    "macro avg": {
      "precision": 0.6022350359587311,
      "recall": 0.655740923733559,
      "f1-score": 0.6183365673701837,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.7006485667679826,
      "recall": 0.6927644600835716,
      "f1-score": 0.6924400502179169,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6814814814814815,
  "macro_f1": 0.6180278003615961,
  "weighted_f1": 0.6796105958247896,
  "per_class_f1": [
    0.46528623629719856,
    0.5226130653266332,
    0.6900584795321637,
    0.8053265694356373,
    0.5919439579684763,
    0.5779543197616683,
    0.6730119742093952
  ],
  "report": {
    "anger": {
      "precision": 0.6345514950166113,
      "recall": 0.36730769230769234,
      "f1-score": 0.46528623629719856,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.42276422764227645,
      "recall": 0.6842105263157895,
      "f1-score": 0.5226130653266332,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6276595744680851,
      "recall": 0.7662337662337663,
      "f1-score": 0.6900584795321637,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8188265635074146,
      "recall": 0.7922645040548971,
      "f1-score": 0.8053265694356373,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5416666666666666,
      "recall": 0.6525096525096525,
      "f1-score": 0.5919439579684763,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.521505376344086,
      "recall": 0.6481069042316259,
      "f1-score": 0.5779543197616683,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.663840096910963,
      "recall": 0.6824408468244084,
      "f1-score": 0.6730119742093952,
      "support": 1606.0
    },
    "accuracy": 0.6814814814814815,
    "macro avg": {
      "precision": 0.6044020000794433,
      "recall": 0.656153413211119,
      "f1-score": 0.6180278003615961,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6892332033834525,
      "recall": 0.6814814814814815,
      "f1-score": 0.6796105958247896,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_random_oversampling_x3_seed0_20260701_163217
================================================================================

--------------------------------------------------------------------------------
Starting random_oversampling_x3 with seed 1
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: random_oversampling_x3
Seed:    1
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_random_oversampling_x3_seed1_20260701_164101
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Augmentation completed in 0.6 seconds (0.01 minutes).

Final training class counts:
ekman_id
0     3878
1     1988
2     2060
3    12920
4     8484
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 512.2 seconds (8.54 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6863866285462943,
  "macro_f1": 0.6174015473932738,
  "weighted_f1": 0.690238129355832,
  "per_class_f1": [
    0.5096262740656852,
    0.5,
    0.6713286713286714,
    0.8054934525710635,
    0.5581395348837209,
    0.6,
    0.6772228989037758
  ],
  "report": {
    "anger": {
      "precision": 0.5653266331658291,
      "recall": 0.4639175257731959,
      "f1-score": 0.5096262740656852,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.42528735632183906,
      "recall": 0.6065573770491803,
      "f1-score": 0.5,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6233766233766234,
      "recall": 0.7272727272727273,
      "f1-score": 0.6713286713286714,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8619275461380724,
      "recall": 0.7559952038369304,
      "f1-score": 0.8054934525710635,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.44554455445544555,
      "recall": 0.7468879668049793,
      "f1-score": 0.5581395348837209,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.6070588235294118,
      "recall": 0.593103448275862,
      "f1-score": 0.6,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6568222090962788,
      "recall": 0.6989314896291641,
      "f1-score": 0.6772228989037758,
      "support": 1591.0
    },
    "accuracy": 0.6863866285462943,
    "macro avg": {
      "precision": 0.5979062494405001,
      "recall": 0.6560951055202914,
      "f1-score": 0.6174015473932738,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.7027523445026297,
      "recall": 0.6863866285462943,
      "f1-score": 0.690238129355832,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6782135076252723,
  "macro_f1": 0.6168432457479224,
  "weighted_f1": 0.6810503602000284,
  "per_class_f1": [
    0.49141630901287553,
    0.5465116279069767,
    0.6666666666666666,
    0.8091300033079722,
    0.5563689604685212,
    0.5769230769230769,
    0.6708860759493671
  ],
  "report": {
    "anger": {
      "precision": 0.5558252427184466,
      "recall": 0.4403846153846154,
      "f1-score": 0.49141630901287553,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.4895833333333333,
      "recall": 0.618421052631579,
      "f1-score": 0.5465116279069767,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6153846153846154,
      "recall": 0.7272727272727273,
      "f1-score": 0.6666666666666666,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8612676056338028,
      "recall": 0.7629444791016844,
      "f1-score": 0.8091300033079722,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.4481132075471698,
      "recall": 0.7335907335907336,
      "f1-score": 0.5563689604685212,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5862068965517241,
      "recall": 0.5679287305122495,
      "f1-score": 0.5769230769230769,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6501168224299065,
      "recall": 0.6930261519302615,
      "f1-score": 0.6708860759493671,
      "support": 1606.0
    },
    "accuracy": 0.6782135076252723,
    "macro avg": {
      "precision": 0.6009282462284283,
      "recall": 0.6490812129176929,
      "f1-score": 0.6168432457479224,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6922853771005223,
      "recall": 0.6782135076252723,
      "f1-score": 0.6810503602000284,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_random_oversampling_x3_seed1_20260701_164101
================================================================================

================================================================================
Finished control experiment: random_oversampling_x3
================================================================================

In [ ]:
bt_single_results = run_one_control_for_all_seeds(
    control_name="bt_single_x1",
)

================================================================================
Running control experiment: bt_single_x1
Seeds: [42, 0, 1]
================================================================================

--------------------------------------------------------------------------------
Starting bt_single_x1 with seed 42
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: bt_single_x1
Seed:    42
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_single_x1_seed42_20260701_164957
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Translating English to pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Generating English back-translation candidates...

Augmentation completed in 876.0 seconds (14.60 minutes).

Final training class counts:
ekman_id
0     3878
1      994
2     1030
3    12920
4     4242
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 448.2 seconds (7.47 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6892456564767979,
  "macro_f1": 0.6246232401646026,
  "weighted_f1": 0.6892361061797627,
  "per_class_f1": [
    0.4959443800695249,
    0.5365853658536586,
    0.6771653543307087,
    0.8100030497102775,
    0.6039783001808319,
    0.5772532188841202,
    0.671433012123096
  ],
  "report": {
    "anger": {
      "precision": 0.5661375661375662,
      "recall": 0.44123711340206184,
      "f1-score": 0.4959443800695249,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.532258064516129,
      "recall": 0.5409836065573771,
      "f1-score": 0.5365853658536586,
      "support": 61.0
    },
    "fear": {
      "precision": 0.7049180327868853,
      "recall": 0.6515151515151515,
      "f1-score": 0.6771653543307087,
      "support": 66.0
    },
    "joy": {
      "precision": 0.824332712600869,
      "recall": 0.7961630695443646,
      "f1-score": 0.8100030497102775,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5352564102564102,
      "recall": 0.6929460580912863,
      "f1-score": 0.6039783001808319,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5412474849094567,
      "recall": 0.6183908045977011,
      "f1-score": 0.5772532188841202,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6642066420664207,
      "recall": 0.6788183532369579,
      "f1-score": 0.671433012123096,
      "support": 1591.0
    },
    "accuracy": 0.6892456564767979,
    "macro avg": {
      "precision": 0.6240509876105339,
      "recall": 0.6314363081349857,
      "f1-score": 0.6246232401646026,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6927090905277044,
      "recall": 0.6892456564767979,
      "f1-score": 0.6892361061797627,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6910675381263617,
  "macro_f1": 0.6148992655091835,
  "weighted_f1": 0.6899544527962955,
  "per_class_f1": [
    0.49557522123893805,
    0.4755244755244755,
    0.6666666666666666,
    0.8140703517587939,
    0.5811965811965812,
    0.5837615621788284,
    0.6875
  ],
  "report": {
    "anger": {
      "precision": 0.5833333333333334,
      "recall": 0.4307692307692308,
      "f1-score": 0.49557522123893805,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.5074626865671642,
      "recall": 0.4473684210526316,
      "f1-score": 0.4755244755244755,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6463414634146342,
      "recall": 0.6883116883116883,
      "f1-score": 0.6666666666666666,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8197343453510436,
      "recall": 0.8084840923268871,
      "f1-score": 0.8140703517587939,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5214723926380368,
      "recall": 0.6563706563706564,
      "f1-score": 0.5811965811965812,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5419847328244275,
      "recall": 0.6325167037861915,
      "f1-score": 0.5837615621788284,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6832718327183271,
      "recall": 0.6917808219178082,
      "f1-score": 0.6875,
      "support": 1606.0
    },
    "accuracy": 0.6910675381263617,
    "macro avg": {
      "precision": 0.6148001124067096,
      "recall": 0.622228802076442,
      "f1-score": 0.6148992655091835,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6931263624989412,
      "recall": 0.6910675381263617,
      "f1-score": 0.6899544527962955,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_single_x1_seed42_20260701_164957
================================================================================

--------------------------------------------------------------------------------
Starting bt_single_x1 with seed 0
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: bt_single_x1
Seed:    0
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_single_x1_seed0_20260701_171219
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Translating English to pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Generating English back-translation candidates...

Augmentation completed in 871.9 seconds (14.53 minutes).

Final training class counts:
ekman_id
0     3878
1      994
2     1030
3    12920
4     4242
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 433.4 seconds (7.22 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6978227402683088,
  "macro_f1": 0.62337241501224,
  "weighted_f1": 0.6969601162932385,
  "per_class_f1": [
    0.5419766206163655,
    0.5,
    0.6466165413533834,
    0.8174015981059485,
    0.6130841121495327,
    0.5693606755126659,
    0.6751673573477845
  ],
  "report": {
    "anger": {
      "precision": 0.5592105263157895,
      "recall": 0.5257731958762887,
      "f1-score": 0.5419766206163655,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.4430379746835443,
      "recall": 0.5737704918032787,
      "f1-score": 0.5,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6417910447761194,
      "recall": 0.6515151515151515,
      "f1-score": 0.6466165413533834,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8071303331385155,
      "recall": 0.8279376498800959,
      "f1-score": 0.8174015981059485,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5578231292517006,
      "recall": 0.6804979253112033,
      "f1-score": 0.6130841121495327,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5989847715736041,
      "recall": 0.542528735632184,
      "f1-score": 0.5693606755126659,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.684993531694696,
      "recall": 0.6656191074795726,
      "f1-score": 0.6751673573477845,
      "support": 1591.0
    },
    "accuracy": 0.6978227402683088,
    "macro avg": {
      "precision": 0.6132816159191384,
      "recall": 0.6382346082139678,
      "f1-score": 0.62337241501224,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6975395832547967,
      "recall": 0.6978227402683088,
      "f1-score": 0.6969601162932385,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6904139433551199,
  "macro_f1": 0.626230661529364,
  "weighted_f1": 0.6879592543645666,
  "per_class_f1": [
    0.5173824130879345,
    0.49056603773584906,
    0.7272727272727273,
    0.8089751364463311,
    0.5985663082437276,
    0.5611175785797439,
    0.6797344293392349
  ],
  "report": {
    "anger": {
      "precision": 0.5524017467248908,
      "recall": 0.48653846153846153,
      "f1-score": 0.5173824130879345,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.46987951807228917,
      "recall": 0.5131578947368421,
      "f1-score": 0.49056603773584906,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6818181818181818,
      "recall": 0.7792207792207793,
      "f1-score": 0.7272727272727273,
      "support": 77.0
    },
    "joy": {
      "precision": 0.7870206489675516,
      "recall": 0.8321896444167186,
      "f1-score": 0.8089751364463311,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5585284280936454,
      "recall": 0.6447876447876448,
      "f1-score": 0.5985663082437276,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5878048780487805,
      "recall": 0.5367483296213809,
      "f1-score": 0.5611175785797439,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6904303147077714,
      "recall": 0.6693648816936488,
      "f1-score": 0.6797344293392349,
      "support": 1606.0
    },
    "accuracy": 0.6904139433551199,
    "macro avg": {
      "precision": 0.6182691023475873,
      "recall": 0.6374296622879251,
      "f1-score": 0.626230661529364,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6872479717878561,
      "recall": 0.6904139433551199,
      "f1-score": 0.6879592543645666,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_single_x1_seed0_20260701_171219
================================================================================

--------------------------------------------------------------------------------
Starting bt_single_x1 with seed 1
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: bt_single_x1
Seed:    1
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_single_x1_seed1_20260701_173424
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Translating English to pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Generating English back-translation candidates...

Augmentation completed in 878.4 seconds (14.64 minutes).

Final training class counts:
ekman_id
0     3878
1      994
2     1030
3    12920
4     4242
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 435.7 seconds (7.26 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6927644600835716,
  "macro_f1": 0.628244166058883,
  "weighted_f1": 0.692784096790392,
  "per_class_f1": [
    0.544891640866873,
    0.48120300751879697,
    0.7058823529411765,
    0.814508994396933,
    0.5949820788530465,
    0.597574421168688,
    0.6586666666666666
  ],
  "report": {
    "anger": {
      "precision": 0.5454545454545454,
      "recall": 0.5443298969072164,
      "f1-score": 0.544891640866873,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.4444444444444444,
      "recall": 0.5245901639344263,
      "f1-score": 0.48120300751879697,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6857142857142857,
      "recall": 0.7272727272727273,
      "f1-score": 0.7058823529411765,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8015089959373186,
      "recall": 0.8279376498800959,
      "f1-score": 0.814508994396933,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5236593059936908,
      "recall": 0.6887966804979253,
      "f1-score": 0.5949820788530465,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5741525423728814,
      "recall": 0.6229885057471264,
      "f1-score": 0.597574421168688,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.7012065294535131,
      "recall": 0.6209930861093652,
      "f1-score": 0.6586666666666666,
      "support": 1591.0
    },
    "accuracy": 0.6927644600835716,
    "macro avg": {
      "precision": 0.6108772356243828,
      "recall": 0.650986958621269,
      "f1-score": 0.628244166058883,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.696153189086074,
      "recall": 0.6927644600835716,
      "f1-score": 0.692784096790392,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6843137254901961,
  "macro_f1": 0.6245525743631505,
  "weighted_f1": 0.6833657610793916,
  "per_class_f1": [
    0.5267249757045676,
    0.5031446540880503,
    0.6909090909090909,
    0.8123486682808717,
    0.59375,
    0.5912863070539419,
    0.6537043245055314
  ],
  "report": {
    "anger": {
      "precision": 0.5324165029469549,
      "recall": 0.5211538461538462,
      "f1-score": 0.5267249757045676,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.4819277108433735,
      "recall": 0.5263157894736842,
      "f1-score": 0.5031446540880503,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6477272727272727,
      "recall": 0.7402597402597403,
      "f1-score": 0.6909090909090909,
      "support": 77.0
    },
    "joy": {
      "precision": 0.7889476778365667,
      "recall": 0.8371802869619464,
      "f1-score": 0.8123486682808717,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5394321766561514,
      "recall": 0.6602316602316602,
      "f1-score": 0.59375,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5533980582524272,
      "recall": 0.6347438752783965,
      "f1-score": 0.5912863070539419,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.7080610021786492,
      "recall": 0.6070983810709838,
      "f1-score": 0.6537043245055314,
      "support": 1606.0
    },
    "accuracy": 0.6843137254901961,
    "macro avg": {
      "precision": 0.6074157716344851,
      "recall": 0.6467119399186083,
      "f1-score": 0.6245525743631505,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6870099883522272,
      "recall": 0.6843137254901961,
      "f1-score": 0.6833657610793916,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_single_x1_seed1_20260701_173424
================================================================================

================================================================================
Finished control experiment: bt_single_x1
================================================================================

In [ ]:
bt_diverse_x2_results = run_one_control_for_all_seeds(
    control_name="bt_diverse_x2",
)

================================================================================
Running control experiment: bt_diverse_x2
Seeds: [42, 0, 1]
================================================================================

--------------------------------------------------------------------------------
Starting bt_diverse_x2 with seed 42
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: bt_diverse_x2
Seed:    42
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_diverse_x2_seed42_20260701_175636
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Translating English to pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Generating English back-translation candidates...

Augmentation completed in 1037.7 seconds (17.30 minutes).

Final training class counts:
ekman_id
0     3878
1     1491
2     1545
3    12920
4     6363
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 472.6 seconds (7.88 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6923246096327249,
  "macro_f1": 0.612767420279688,
  "weighted_f1": 0.693594355647491,
  "per_class_f1": [
    0.548,
    0.463768115942029,
    0.6193548387096774,
    0.8156558111741858,
    0.5857142857142857,
    0.5904317386231038,
    0.6664471517945341
  ],
  "report": {
    "anger": {
      "precision": 0.5320388349514563,
      "recall": 0.5649484536082474,
      "f1-score": 0.548,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.4155844155844156,
      "recall": 0.5245901639344263,
      "f1-score": 0.463768115942029,
      "support": 61.0
    },
    "fear": {
      "precision": 0.5393258426966292,
      "recall": 0.7272727272727273,
      "f1-score": 0.6193548387096774,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8129839189994044,
      "recall": 0.8183453237410072,
      "f1-score": 0.8156558111741858,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5141065830721003,
      "recall": 0.6804979253112033,
      "f1-score": 0.5857142857142857,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5995260663507109,
      "recall": 0.5816091954022988,
      "f1-score": 0.5904317386231038,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6998616874135546,
      "recall": 0.6360779384035198,
      "f1-score": 0.6664471517945341,
      "support": 1591.0
    },
    "accuracy": 0.6923246096327249,
    "macro avg": {
      "precision": 0.5876324784383246,
      "recall": 0.64762024681049,
      "f1-score": 0.612767420279688,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6978701642553311,
      "recall": 0.6923246096327249,
      "f1-score": 0.693594355647491,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6864923747276689,
  "macro_f1": 0.6216461016878565,
  "weighted_f1": 0.6868865615593337,
  "per_class_f1": [
    0.5343367826904986,
    0.5189873417721519,
    0.6702702702702703,
    0.8123660850933578,
    0.5626072041166381,
    0.5845147219193021,
    0.6684403059527768
  ],
  "report": {
    "anger": {
      "precision": 0.5230202578268877,
      "recall": 0.5461538461538461,
      "f1-score": 0.5343367826904986,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.5,
      "recall": 0.5394736842105263,
      "f1-score": 0.5189873417721519,
      "support": 76.0
    },
    "fear": {
      "precision": 0.5740740740740741,
      "recall": 0.8051948051948052,
      "f1-score": 0.6702702702702703,
      "support": 77.0
    },
    "joy": {
      "precision": 0.7974759615384616,
      "recall": 0.8278228321896444,
      "f1-score": 0.8123660850933578,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5061728395061729,
      "recall": 0.6332046332046332,
      "f1-score": 0.5626072041166381,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5726495726495726,
      "recall": 0.5968819599109132,
      "f1-score": 0.5845147219193021,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.7173447537473233,
      "recall": 0.6257783312577833,
      "f1-score": 0.6684403059527768,
      "support": 1606.0
    },
    "accuracy": 0.6864923747276689,
    "macro avg": {
      "precision": 0.5986767799060703,
      "recall": 0.653501441731736,
      "f1-score": 0.6216461016878565,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6912423316317641,
      "recall": 0.6864923747276689,
      "f1-score": 0.6868865615593337,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_diverse_x2_seed42_20260701_175636
================================================================================

--------------------------------------------------------------------------------
Starting bt_diverse_x2 with seed 0
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: bt_diverse_x2
Seed:    0
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_diverse_x2_seed0_20260701_182204
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Translating English to pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Generating English back-translation candidates...

Augmentation completed in 1030.7 seconds (17.18 minutes).

Final training class counts:
ekman_id
0     3878
1     1491
2     1545
3    12920
4     6363
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 466.5 seconds (7.77 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6916648339564548,
  "macro_f1": 0.6130845559037733,
  "weighted_f1": 0.6940871114107896,
  "per_class_f1": [
    0.5297872340425532,
    0.48,
    0.625,
    0.8160637645616187,
    0.5704347826086956,
    0.5979142526071842,
    0.6723918575063613
  ],
  "report": {
    "anger": {
      "precision": 0.5472527472527473,
      "recall": 0.51340206185567,
      "f1-score": 0.5297872340425532,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.4044943820224719,
      "recall": 0.5901639344262295,
      "f1-score": 0.48,
      "support": 61.0
    },
    "fear": {
      "precision": 0.5319148936170213,
      "recall": 0.7575757575757576,
      "f1-score": 0.625,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8350062735257214,
      "recall": 0.7979616306954437,
      "f1-score": 0.8160637645616187,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.49101796407185627,
      "recall": 0.6804979253112033,
      "f1-score": 0.5704347826086956,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.602803738317757,
      "recall": 0.593103448275862,
      "f1-score": 0.5979142526071842,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6806181584030908,
      "recall": 0.6643620364550598,
      "f1-score": 0.6723918575063613,
      "support": 1591.0
    },
    "accuracy": 0.6916648339564548,
    "macro avg": {
      "precision": 0.5847297367443808,
      "recall": 0.656723827799318,
      "f1-score": 0.6130845559037733,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6996716587792916,
      "recall": 0.6916648339564548,
      "f1-score": 0.6940871114107896,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6821350762527233,
  "macro_f1": 0.6196355702943303,
  "weighted_f1": 0.6829260228398775,
  "per_class_f1": [
    0.520242914979757,
    0.5207100591715976,
    0.6850828729281768,
    0.8076561029181047,
    0.5518394648829431,
    0.5846153846153846,
    0.667302192564347
  ],
  "report": {
    "anger": {
      "precision": 0.5491452991452992,
      "recall": 0.49423076923076925,
      "f1-score": 0.520242914979757,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.4731182795698925,
      "recall": 0.5789473684210527,
      "f1-score": 0.5207100591715976,
      "support": 76.0
    },
    "fear": {
      "precision": 0.5961538461538461,
      "recall": 0.8051948051948052,
      "f1-score": 0.6850828729281768,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8125,
      "recall": 0.8028696194635059,
      "f1-score": 0.8076561029181047,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.48672566371681414,
      "recall": 0.637065637065637,
      "f1-score": 0.5518394648829431,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5770065075921909,
      "recall": 0.5924276169265034,
      "f1-score": 0.5846153846153846,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6813757300454251,
      "recall": 0.6537982565379825,
      "f1-score": 0.667302192564347,
      "support": 1606.0
    },
    "accuracy": 0.6821350762527233,
    "macro avg": {
      "precision": 0.5965750466033526,
      "recall": 0.6520762961200365,
      "f1-score": 0.6196355702943303,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6861179046233583,
      "recall": 0.6821350762527233,
      "f1-score": 0.6829260228398775,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_diverse_x2_seed0_20260701_182204
================================================================================

--------------------------------------------------------------------------------
Starting bt_diverse_x2 with seed 1
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: bt_diverse_x2
Seed:    1
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_diverse_x2_seed1_20260701_184721
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Translating English to pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Generating English back-translation candidates...

Augmentation completed in 1020.9 seconds (17.01 minutes).

Final training class counts:
ekman_id
0     3878
1     1491
2     1545
3    12920
4     6363
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 479.8 seconds (8.00 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6830877501649439,
  "macro_f1": 0.5980178376218055,
  "weighted_f1": 0.6829180185967589,
  "per_class_f1": [
    0.4774774774774775,
    0.4714285714285714,
    0.647887323943662,
    0.8133619368679129,
    0.5483870967741935,
    0.5534591194968553,
    0.6741233373639661
  ],
  "report": {
    "anger": {
      "precision": 0.5260545905707196,
      "recall": 0.43711340206185567,
      "f1-score": 0.4774774774774775,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.4177215189873418,
      "recall": 0.5409836065573771,
      "f1-score": 0.4714285714285714,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6052631578947368,
      "recall": 0.696969696969697,
      "f1-score": 0.647887323943662,
      "support": 66.0
    },
    "joy": {
      "precision": 0.831974921630094,
      "recall": 0.7955635491606715,
      "f1-score": 0.8133619368679129,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.48264984227129337,
      "recall": 0.6348547717842323,
      "f1-score": 0.5483870967741935,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.6111111111111112,
      "recall": 0.5057471264367817,
      "f1-score": 0.5534591194968553,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6493884682585905,
      "recall": 0.7008170961659334,
      "f1-score": 0.6741233373639661,
      "support": 1591.0
    },
    "accuracy": 0.6830877501649439,
    "macro avg": {
      "precision": 0.5891662301034124,
      "recall": 0.6160070355909355,
      "f1-score": 0.5980178376218055,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6869645975599756,
      "recall": 0.6830877501649439,
      "f1-score": 0.6829180185967589,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6856209150326797,
  "macro_f1": 0.6107287342639538,
  "weighted_f1": 0.6842958046078529,
  "per_class_f1": [
    0.5047518479408659,
    0.48148148148148145,
    0.6666666666666666,
    0.8079220370952531,
    0.5632798573975044,
    0.5700712589073634,
    0.6809279903585417
  ],
  "report": {
    "anger": {
      "precision": 0.5597189695550351,
      "recall": 0.4596153846153846,
      "f1-score": 0.5047518479408659,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.45348837209302323,
      "recall": 0.5131578947368421,
      "f1-score": 0.48148148148148145,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6153846153846154,
      "recall": 0.7272727272727273,
      "f1-score": 0.6666666666666666,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8143219264892269,
      "recall": 0.801621958827199,
      "f1-score": 0.8079220370952531,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5231788079470199,
      "recall": 0.61003861003861,
      "f1-score": 0.5632798573975044,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.6106870229007634,
      "recall": 0.534521158129176,
      "f1-score": 0.5700712589073634,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6596614127262114,
      "recall": 0.7036114570361146,
      "f1-score": 0.6809279903585417,
      "support": 1606.0
    },
    "accuracy": 0.6856209150326797,
    "macro avg": {
      "precision": 0.6052058752994135,
      "recall": 0.6214055986651505,
      "f1-score": 0.6107287342639538,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6857036290574183,
      "recall": 0.6856209150326797,
      "f1-score": 0.6842958046078529,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_diverse_x2_seed1_20260701_184721
================================================================================

================================================================================
Finished control experiment: bt_diverse_x2
================================================================================

In [ ]:
bt_similarity_filtered_results = run_one_control_for_all_seeds(
    control_name="bt_similarity_filtered_x3",
)

================================================================================
Running control experiment: bt_similarity_filtered_x3
Seeds: [42, 0, 1]
================================================================================

--------------------------------------------------------------------------------
Starting bt_similarity_filtered_x3 with seed 42
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: bt_similarity_filtered_x3
Seed:    42
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_similarity_filtered_x3_seed42_20260701_191238
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Translating English to pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Generating English back-translation candidates...

Computing semantic similarities...

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/665 [00:00<?, ?it/s]

Batches:   0%|          | 0/665 [00:00<?, ?it/s]

Augmentation completed in 1211.0 seconds (20.18 minutes).

Final training class counts:
ekman_id
0     3878
1     1988
2     2060
3    12920
4     8484
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 503.6 seconds (8.39 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6815482735869804,
  "macro_f1": 0.5872233781200661,
  "weighted_f1": 0.679734490902348,
  "per_class_f1": [
    0.4339869281045752,
    0.41711229946524064,
    0.6356589147286822,
    0.8092413362472682,
    0.5756457564575646,
    0.5595092024539877,
    0.6794092093831451
  ],
  "report": {
    "anger": {
      "precision": 0.5928571428571429,
      "recall": 0.3422680412371134,
      "f1-score": 0.4339869281045752,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.30952380952380953,
      "recall": 0.639344262295082,
      "f1-score": 0.41711229946524064,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6507936507936508,
      "recall": 0.6212121212121212,
      "f1-score": 0.6356589147286822,
      "support": 66.0
    },
    "joy": {
      "precision": 0.844299674267101,
      "recall": 0.7769784172661871,
      "f1-score": 0.8092413362472682,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5182724252491694,
      "recall": 0.6473029045643154,
      "f1-score": 0.5756457564575646,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.6,
      "recall": 0.5241379310344828,
      "f1-score": 0.5595092024539877,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6299677765843179,
      "recall": 0.7372721558768071,
      "f1-score": 0.6794092093831451,
      "support": 1591.0
    },
    "accuracy": 0.6815482735869804,
    "macro avg": {
      "precision": 0.5922449256107417,
      "recall": 0.6126451190694441,
      "f1-score": 0.5872233781200661,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6918502949917026,
      "recall": 0.6815482735869804,
      "f1-score": 0.679734490902348,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6851851851851852,
  "macro_f1": 0.6092295933556275,
  "weighted_f1": 0.6832387893561005,
  "per_class_f1": [
    0.47101449275362317,
    0.49523809523809526,
    0.6496815286624203,
    0.8055826030509575,
    0.5843478260869566,
    0.5710982658959538,
    0.6876443418013857
  ],
  "report": {
    "anger": {
      "precision": 0.6331168831168831,
      "recall": 0.375,
      "f1-score": 0.47101449275362317,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.3880597014925373,
      "recall": 0.6842105263157895,
      "f1-score": 0.49523809523809526,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6375,
      "recall": 0.6623376623376623,
      "f1-score": 0.6496815286624203,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8396481732070366,
      "recall": 0.7741734248284466,
      "f1-score": 0.8055826030509575,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5316455696202531,
      "recall": 0.6486486486486487,
      "f1-score": 0.5843478260869566,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.59375,
      "recall": 0.5501113585746102,
      "f1-score": 0.5710982658959538,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6410118406889128,
      "recall": 0.7415940224159402,
      "f1-score": 0.6876443418013857,
      "support": 1606.0
    },
    "accuracy": 0.6851851851851852,
    "macro avg": {
      "precision": 0.6092474525893747,
      "recall": 0.6337250918744425,
      "f1-score": 0.6092295933556275,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6944470167457801,
      "recall": 0.6851851851851852,
      "f1-score": 0.6832387893561005,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_similarity_filtered_x3_seed42_20260701_191238
================================================================================

--------------------------------------------------------------------------------
Starting bt_similarity_filtered_x3 with seed 0
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: bt_similarity_filtered_x3
Seed:    0
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_similarity_filtered_x3_seed0_20260701_194129
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Translating English to pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Generating English back-translation candidates...

Computing semantic similarities...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/662 [00:00<?, ?it/s]

Batches:   0%|          | 0/662 [00:00<?, ?it/s]

Augmentation completed in 1196.7 seconds (19.95 minutes).

Final training class counts:
ekman_id
0     3878
1     1988
2     2060
3    12920
4     8484
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 499.1 seconds (8.32 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.6822080492632505,
  "macro_f1": 0.6062826708060746,
  "weighted_f1": 0.6851923299839444,
  "per_class_f1": [
    0.47268408551068886,
    0.5032258064516129,
    0.6535947712418301,
    0.8106060606060606,
    0.5475040257648953,
    0.579957356076759,
    0.6764065899906745
  ],
  "report": {
    "anger": {
      "precision": 0.5574229691876751,
      "recall": 0.41030927835051545,
      "f1-score": 0.47268408551068886,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.4148936170212766,
      "recall": 0.639344262295082,
      "f1-score": 0.5032258064516129,
      "support": 61.0
    },
    "fear": {
      "precision": 0.5747126436781609,
      "recall": 0.7575757575757576,
      "f1-score": 0.6535947712418301,
      "support": 66.0
    },
    "joy": {
      "precision": 0.856,
      "recall": 0.7697841726618705,
      "f1-score": 0.8106060606060606,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.4473684210526316,
      "recall": 0.7053941908713693,
      "f1-score": 0.5475040257648953,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5407554671968191,
      "recall": 0.6252873563218391,
      "f1-score": 0.579957356076759,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6691266912669127,
      "recall": 0.6838466373350094,
      "f1-score": 0.6764065899906745,
      "support": 1591.0
    },
    "accuracy": 0.6822080492632505,
    "macro avg": {
      "precision": 0.5800399727719251,
      "recall": 0.6559345222016348,
      "f1-score": 0.6062826708060746,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6969480247827221,
      "recall": 0.6822080492632505,
      "f1-score": 0.6851923299839444,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6736383442265795,
  "macro_f1": 0.6116338952693344,
  "weighted_f1": 0.6762018131100191,
  "per_class_f1": [
    0.48027057497181513,
    0.5207100591715976,
    0.6775956284153005,
    0.8047571853320119,
    0.5564142194744977,
    0.5756385068762279,
    0.6660510926438904
  ],
  "report": {
    "anger": {
      "precision": 0.5803814713896458,
      "recall": 0.4096153846153846,
      "f1-score": 0.48027057497181513,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.4731182795698925,
      "recall": 0.5789473684210527,
      "f1-score": 0.5207100591715976,
      "support": 76.0
    },
    "fear": {
      "precision": 0.5849056603773585,
      "recall": 0.8051948051948052,
      "f1-score": 0.6775956284153005,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8553370786516854,
      "recall": 0.759825327510917,
      "f1-score": 0.8047571853320119,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.4639175257731959,
      "recall": 0.694980694980695,
      "f1-score": 0.5564142194744977,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5149384885764499,
      "recall": 0.6525612472160356,
      "f1-score": 0.5756385068762279,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6585514303104077,
      "recall": 0.6737235367372354,
      "f1-score": 0.6660510926438904,
      "support": 1606.0
    },
    "accuracy": 0.6736383442265795,
    "macro avg": {
      "precision": 0.5901642763783765,
      "recall": 0.6535497663823036,
      "f1-score": 0.6116338952693344,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6890836699176982,
      "recall": 0.6736383442265795,
      "f1-score": 0.6762018131100191,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_similarity_filtered_x3_seed0_20260701_194129
================================================================================

--------------------------------------------------------------------------------
Starting bt_similarity_filtered_x3 with seed 1
--------------------------------------------------------------------------------
================================================================================
PHASE 4 BACK-TRANSLATION CONTROL EXPERIMENT
================================================================================
Control: bt_similarity_filtered_x3
Seed:    1
Output:  /content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_similarity_filtered_x3_seed1_20260701_201005
================================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Original training class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Translating English to pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Generating English back-translation candidates...

Computing semantic similarities...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/663 [00:00<?, ?it/s]

Batches:   0%|          | 0/663 [00:00<?, ?it/s]

Augmentation completed in 1195.7 seconds (19.93 minutes).

Final training class counts:
ekman_id
0     3878
1     1988
2     2060
3    12920
4     8484
5     3553
6    12818

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 497.4 seconds (8.29 minutes).
Peak GPU memory: 3.28 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

================================================================================
FINAL RESULTS
================================================================================

Validation metrics:
{
  "accuracy": 0.674510666373433,
  "macro_f1": 0.595195001408575,
  "weighted_f1": 0.6795471296846652,
  "per_class_f1": [
    0.4845005740528129,
    0.4311377245508982,
    0.6762589928057554,
    0.8082148499210111,
    0.5227606461086637,
    0.5782857142857143,
    0.6652065081351689
  ],
  "report": {
    "anger": {
      "precision": 0.5466321243523317,
      "recall": 0.4350515463917526,
      "f1-score": 0.4845005740528129,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.33962264150943394,
      "recall": 0.5901639344262295,
      "f1-score": 0.4311377245508982,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6438356164383562,
      "recall": 0.7121212121212122,
      "f1-score": 0.6762589928057554,
      "support": 66.0
    },
    "joy": {
      "precision": 0.85437541750167,
      "recall": 0.7667865707434053,
      "f1-score": 0.8082148499210111,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.40454545454545454,
      "recall": 0.7385892116182573,
      "f1-score": 0.5227606461086637,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.575,
      "recall": 0.5816091954022988,
      "f1-score": 0.5782857142857143,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6623052959501557,
      "recall": 0.6681332495285983,
      "f1-score": 0.6652065081351689,
      "support": 1591.0
    },
    "accuracy": 0.674510666373433,
    "macro avg": {
      "precision": 0.5751880786139145,
      "recall": 0.6417792743188221,
      "f1-score": 0.595195001408575,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6938141827408897,
      "recall": 0.674510666373433,
      "f1-score": 0.6795471296846652,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6671023965141613,
  "macro_f1": 0.6112377571849111,
  "weighted_f1": 0.671650278105656,
  "per_class_f1": [
    0.48452508004268946,
    0.5405405405405406,
    0.7133757961783439,
    0.8053559764859569,
    0.5061898211829436,
    0.5708154506437768,
    0.6578616352201258
  ],
  "report": {
    "anger": {
      "precision": 0.5443645083932853,
      "recall": 0.43653846153846154,
      "f1-score": 0.48452508004268946,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.45871559633027525,
      "recall": 0.6578947368421053,
      "f1-score": 0.5405405405405406,
      "support": 76.0
    },
    "fear": {
      "precision": 0.7,
      "recall": 0.7272727272727273,
      "f1-score": 0.7133757961783439,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8450993831391364,
      "recall": 0.769182782283219,
      "f1-score": 0.8053559764859569,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.39316239316239315,
      "recall": 0.7104247104247104,
      "f1-score": 0.5061898211829436,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5507246376811594,
      "recall": 0.5924276169265034,
      "f1-score": 0.5708154506437768,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6645489199491741,
      "recall": 0.651307596513076,
      "f1-score": 0.6578616352201258,
      "support": 1606.0
    },
    "accuracy": 0.6671023965141613,
    "macro avg": {
      "precision": 0.5938022055222033,
      "recall": 0.649292661685829,
      "f1-score": 0.6112377571849111,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.684726847155538,
      "recall": 0.6671023965141613,
      "f1-score": 0.671650278105656,
      "support": 4590.0
    }
  }
}

All results saved in:
/content/drive/MyDrive/Thesis/results/phase4_bt_control_runs/phase4_control_bt_similarity_filtered_x3_seed1_20260701_201005
================================================================================

================================================================================
Finished control experiment: bt_similarity_filtered_x3
================================================================================

In [ ]:
def collect_control_results(output_root):
    output_root = Path(output_root)

    rows = []

    for result_file in output_root.glob(
        "phase4_control_*/complete_results.json"
    ):
        with open(
            result_file,
            "r",
            encoding="utf-8",
        ) as file:
            result = json.load(file)

        row = {
            "run_name": result["run_name"],
            "control_name": result["control_name"],
            "seed": result["seed"],
            "generated_synthetic_examples": result[
                "generated_synthetic_examples"
            ],
            "final_training_size": result[
                "final_training_size"
            ],
            "best_validation_macro_f1": result[
                "best_validation_macro_f1_during_training"
            ],
            "validation_accuracy": result[
                "validation"
            ]["accuracy"],
            "validation_macro_f1": result[
                "validation"
            ]["macro_f1"],
            "validation_weighted_f1": result[
                "validation"
            ]["weighted_f1"],
            "test_accuracy": result[
                "test"
            ]["accuracy"],
            "test_macro_f1": result[
                "test"
            ]["macro_f1"],
            "test_weighted_f1": result[
                "test"
            ]["weighted_f1"],
        }

        augmentation = result.get(
            "augmentation",
            {},
        )

        row["selected_class_ids"] = augmentation.get(
            "selected_class_ids"
        )

        row["mean_semantic_similarity"] = augmentation.get(
            "mean_semantic_similarity"
        )

        row["passed_similarity_filter_count"] = augmentation.get(
            "passed_similarity_filter_count"
        )

        row["sources_with_insufficient_passing_candidates"] = augmentation.get(
            "sources_with_insufficient_passing_candidates"
        )

        rows.append(row)

    summary_df = pd.DataFrame(rows)

    if len(summary_df) == 0:
        raise FileNotFoundError(
            f"No complete_results.json files found under {output_root}"
        )

    summary_df = summary_df.sort_values(
        [
            "control_name",
            "seed",
        ]
    ).reset_index(drop=True)

    return summary_df


control_summary = collect_control_results(
    OUTPUT_ROOT
)

control_summary.to_csv(
    OUTPUT_ROOT / "phase4_bt_control_summary_by_seed.csv",
    index=False,
)

control_summary

,run_name,control_name,seed,generated_synthetic_examples,final_training_size,best_validation_macro_f1,validation_accuracy,validation_macro_f1,validation_weighted_f1,test_accuracy,test_macro_f1,test_weighted_f1,selected_class_ids,mean_semantic_similarity,passed_similarity_filter_count,sources_with_insufficient_passing_candidates
0,phase4_control_bt_diverse_x2_seed0_20260701_18...,bt_diverse_x2,0,6266,42568,0.613085,0.691665,0.613085,0.694087,0.682135,0.619636,0.682926,"[1, 2, 4]",NaN,NaN,NaN
1,phase4_control_bt_diverse_x2_seed1_20260701_18...,bt_diverse_x2,1,6266,42568,0.598018,0.683088,0.598018,0.682918,0.685621,0.610729,0.684296,"[1, 2, 4]",NaN,NaN,NaN
2,phase4_control_bt_diverse_x2_seed42_20260701_1...,bt_diverse_x2,42,6266,42568,0.612767,0.692325,0.612767,0.693594,0.686492,0.621646,0.686887,"[1, 2, 4]",NaN,NaN,NaN
3,phase4_control_bt_similarity_filtered_x3_seed0...,bt_similarity_filtered_x3,0,9399,45701,0.606283,0.682208,0.606283,0.685192,0.673638,0.611634,0.676202,"[1, 2, 4]",0.874564,8106.0,520.0
4,phase4_control_bt_similarity_filtered_x3_seed1...,bt_similarity_filtered_x3,1,9399,45701,0.595195,0.674511,0.595195,0.679547,0.667102,0.611238,0.671650,"[1, 2, 4]",0.874653,8114.0,520.0
5,phase4_control_bt_similarity_filtered_x3_seed4...,bt_similarity_filtered_x3,42,9399,45701,0.587223,0.681548,0.587223,0.679734,0.685185,0.609230,0.683239,"[1, 2, 4]",0.874537,8125.0,520.0
6,phase4_control_bt_single_x1_seed0_20260701_171219,bt_single_x1,0,3133,39435,0.623372,0.697823,0.623372,0.696960,0.690414,0.626231,0.687959,"[1, 2, 4]",NaN,NaN,NaN
7,phase4_control_bt_single_x1_seed1_20260701_173424,bt_single_x1,1,3133,39435,0.628244,0.692764,0.628244,0.692784,0.684314,0.624553,0.683366,"[1, 2, 4]",NaN,NaN,NaN
8,phase4_control_bt_single_x1_seed42_20260701_16...,bt_single_x1,42,3133,39435,0.624623,0.689246,0.624623,0.689236,0.691068,0.614899,0.689954,"[1, 2, 4]",NaN,NaN,NaN
9,phase4_control_direct_duplication_x3_seed0_202...,direct_duplication_x3,0,9399,45701,0.612440,0.685727,0.612440,0.686290,0.676035,0.618182,0.675187,"[1, 2, 4]",NaN,NaN,NaN
10,phase4_control_direct_duplication_x3_seed0_202...,direct_duplication_x3,0,9399,45701,0.612440,0.685727,0.612440,0.686290,0.676035,0.618182,0.675187,"[1, 2, 4]",NaN,NaN,NaN
11,phase4_control_direct_duplication_x3_seed1_202...,direct_duplication_x3,1,9399,45701,0.599759,0.688586,0.599759,0.689469,0.684314,0.611880,0.683519,"[1, 2, 4]",NaN,NaN,NaN
12,phase4_control_direct_duplication_x3_seed1_202...,direct_duplication_x3,1,9399,45701,0.599759,0.688586,0.599759,0.689469,0.684314,0.611880,0.683519,"[1, 2, 4]",NaN,NaN,NaN
13,phase4_control_direct_duplication_x3_seed42_20...,direct_duplication_x3,42,9399,45701,0.609546,0.691005,0.609546,0.691695,0.684967,0.612214,0.684536,"[1, 2, 4]",NaN,NaN,NaN
14,phase4_control_direct_duplication_x3_seed42_20...,direct_duplication_x3,42,9399,45701,0.609546,0.691005,0.609546,0.691695,0.684967,0.612214,0.684536,"[1, 2, 4]",NaN,NaN,NaN
15,phase4_control_random_oversampling_x3_seed0_20...,random_oversampling_x3,0,9399,45701,0.618337,0.692764,0.618337,0.692440,0.681481,0.618028,0.679611,"[1, 2, 4]",NaN,NaN,NaN
16,phase4_control_random_oversampling_x3_seed0_20...,random_oversampling_x3,0,9399,45701,0.618337,0.692764,0.618337,0.692440,0.681481,0.618028,0.679611,"[1, 2, 4]",NaN,NaN,NaN
17,phase4_control_random_oversampling_x3_seed1_20...,random_oversampling_x3,1,9399,45701,0.617402,0.686387,0.617402,0.690238,0.678214,0.616843,0.681050,"[1, 2, 4]",NaN,NaN,NaN
18,phase4_control_random_oversampling_x3_seed1_20...,random_oversampling_x3,1,9399,45701,0.617402,0.686387,0.617402,0.690238,0.678214,0.616843,0.681050,"[1, 2, 4]",NaN,NaN,NaN
19,phase4_control_random_oversampling_x3_seed42_2...,random_oversampling_x3,42,9399,45701,0.619406,0.695623,0.619406,0.695985,0.685621,0.616240,0.685069,"[1, 2, 4]",NaN,NaN,NaN
20,phase4_control_random_oversampling_x3_seed42_2...,random_oversampling_x3,42,9399,45701,0.619406,0.695623,0.619406,0.695985,0.685621,0.616240,0.685069,"[1, 2, 4]",NaN,NaN,NaN

In [ ]:
summary_by_control = (
    control_summary
    .groupby("control_name")
    .agg(
        seeds=("seed", "count"),
        generated_synthetic_examples_mean=(
            "generated_synthetic_examples",
            "mean",
        ),
        validation_macro_f1_mean=(
            "validation_macro_f1",
            "mean",
        ),
        validation_macro_f1_std=(
            "validation_macro_f1",
            "std",
        ),
        test_macro_f1_mean=(
            "test_macro_f1",
            "mean",
        ),
        test_macro_f1_std=(
            "test_macro_f1",
            "std",
        ),
        test_accuracy_mean=(
            "test_accuracy",
            "mean",
        ),
        test_accuracy_std=(
            "test_accuracy",
            "std",
        ),
        mean_semantic_similarity=(
            "mean_semantic_similarity",
            "mean",
        ),
        passed_similarity_filter_count_mean=(
            "passed_similarity_filter_count",
            "mean",
        ),
    )
    .reset_index()
)

summary_by_control.to_csv(
    OUTPUT_ROOT / "phase4_bt_control_summary_mean_std.csv",
    index=False,
)

summary_by_control

,control_name,seeds,generated_synthetic_examples_mean,validation_macro_f1_mean,validation_macro_f1_std,test_macro_f1_mean,test_macro_f1_std,test_accuracy_mean,test_accuracy_std,mean_semantic_similarity,passed_similarity_filter_count_mean
0,bt_diverse_x2,3,6266.0,0.607957,0.008609,0.617337,0.005810,0.684749,0.002306,NaN,NaN
1,bt_similarity_filtered_x3,3,9399.0,0.596234,0.009572,0.610700,0.001289,0.675309,0.009156,0.874584,8115.0
2,bt_single_x1,3,3133.0,0.625413,0.002530,0.621894,0.006116,0.688598,0.003725,NaN,NaN
3,direct_duplication_x3,6,9399.0,0.607248,0.005944,0.614092,0.003172,0.681772,0.004454,NaN,NaN
4,random_oversampling_x3,6,9399.0,0.618381,0.000897,0.617037,0.000814,0.681772,0.003320,NaN,NaN