In [ ]:
import sys
import os
import importlib
from pathlib import Path
from datetime import datetime
importlib.invalidate_caches()

target_path = '/content/drive/MyDrive/Thesis/models'
if target_path not in sys.path:
    sys.path.insert(0, target_path)

import time
import argparse
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from collections import Counter
from torch.utils.data import Dataset
from transformers import (
    AutoTokenizer, AutoModelForSequenceClassification,
    Trainer, TrainingArguments, DataCollatorWithPadding,
)
from sklearn.metrics import f1_score, accuracy_score

from utils import DATA_DIR, MODELS_DIR, EKMAN_LABELS, set_all_seeds
from evaluate import compute_metrics, save_metrics, plot_confusion_matrix
from train_phase3 import (
    GoEmotionsDataset, hf_compute_metrics, load_data,
    MODEL_NAME, MAX_LENGTH, BATCH_SIZE, N_EPOCHS, LR, WEIGHT_DECAY, WARMUP,
    NUM_LABELS,
)

In [ ]:
import numpy as np
import torch
import torch.nn.functional as F

from transformers import Trainer


def compute_class_weights(
    labels,
    num_labels=NUM_LABELS,
) -> torch.Tensor:
    labels = np.asarray(
        labels,
        dtype=np.int64,
    )

    if labels.ndim != 1:
        raise ValueError(
            "Class labels must be a one-dimensional array."
        )

    if len(labels) == 0:
        raise ValueError(
            "Cannot compute class weights from an empty training-label array. "
        )

    if labels.min() < 0:
        raise ValueError(
            "Class labels cannot contain negative values."
        )

    if labels.max() >= num_labels:
        raise ValueError(
            f"Found class ID {labels.max()}, but NUM_LABELS "
            f"is {num_labels}. Valid IDs are "
            f"0 through {num_labels - 1}."
        )

    class_counts = np.bincount(
        labels,
        minlength=num_labels,
    )

    missing_classes = np.where(
        class_counts == 0
    )[0]

    if len(missing_classes) > 0:
        raise ValueError(
            "The following classes are absent from the "
            f"training set: {missing_classes.tolist()}. "
            "Class weights cannot be calculated safely."
        )

    number_of_examples = len(labels)
    number_of_classes = num_labels

    class_weights = (
        number_of_examples
        / (
            number_of_classes
            * class_counts
        )
    )

    print("\nTraining class counts:")
    for class_id, count in enumerate(
        class_counts
    ):
        class_name = EKMAN_LABELS[class_id]

        print(
            f"{class_id}: {class_name:<10} "
            f"count={count:<6} "
            f"weight={class_weights[class_id]:.6f}"
        )

    return torch.tensor(
        class_weights,
        dtype=torch.float32,
    )


class WeightedCETrainer(Trainer):

    def __init__(
        self,
        *args,
        class_weights=None,
        **kwargs,
    ):
        if class_weights is None:
            raise ValueError(
                "class_weights must be provided to "
                "WeightedCETrainer."
            )

        super().__init__(
            *args,
            **kwargs,
        )

        if not isinstance(
            class_weights,
            torch.Tensor,
        ):
            class_weights = torch.tensor(
                class_weights,
                dtype=torch.float32,
            )

        if class_weights.ndim != 1:
            raise ValueError(
                "class_weights must be one-dimensional."
            )

        if len(class_weights) != NUM_LABELS:
            raise ValueError(
                f"Expected {NUM_LABELS} class weights, "
                f"but received {len(class_weights)}."
            )

        if not torch.all(
            torch.isfinite(class_weights)
        ):
            raise ValueError(
                "Class weights contain NaN or infinity."
            )

        if torch.any(class_weights <= 0):
            raise ValueError(
                "Every class weight must be positive."
            )

        self.class_weights = (
            class_weights
            .detach()
            .clone()
            .to(dtype=torch.float32)
        )

        self.model_accepts_loss_kwargs = False

    def compute_loss(
        self,
        model,
        inputs,
        return_outputs=False,
        num_items_in_batch=None,
        **kwargs,
    ):
        model_inputs = dict(inputs)

        labels = model_inputs.pop(
            "labels"
        ).long()

        outputs = model(
            **model_inputs
        )

        logits = outputs.logits

        if logits.ndim != 2:
            raise ValueError(
                "Expected logits with shape "
                "[batch_size, NUM_LABELS], but received "
                f"{tuple(logits.shape)}."
            )

        if logits.shape[-1] != NUM_LABELS:
            raise ValueError(
                f"Expected {NUM_LABELS} output logits, "
                f"but received {logits.shape[-1]}."
            )

        weights = self.class_weights.to(
            device=logits.device,
        )

        loss = F.cross_entropy(
            input=logits,
            target=labels,
            weight=weights,
            reduction="mean",
        )

        return (
            (loss, outputs)
            if return_outputs
            else loss
        )

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from transformers import Trainer


class FocalLoss(nn.Module):

    def __init__(
        self,
        gamma: float = 2.0,
        alpha: float = 1.0,
        reduction: str = "mean",
    ):
        super().__init__()

        if gamma < 0:
            raise ValueError(
                "gamma must be greater than or equal to zero."
            )

        if alpha <= 0:
            raise ValueError(
                "alpha must be greater than zero."
            )

        if reduction not in {
            "none",
            "mean",
            "sum",
        }:
            raise ValueError(
                "reduction must be 'none', 'mean', or 'sum'."
            )

        self.gamma = float(gamma)
        self.alpha = float(alpha)
        self.reduction = reduction

    def forward(
        self,
        logits: torch.Tensor,
        targets: torch.Tensor,
    ) -> torch.Tensor:

        if logits.ndim != 2:
            raise ValueError(
                "Expected logits with shape "
                "[batch_size, number_of_classes], "
                f"but received {tuple(logits.shape)}."
            )

        if targets.ndim != 1:
            raise ValueError(
                "Expected targets with shape [batch_size], "
                f"but received {tuple(targets.shape)}."
            )

        if logits.shape[0] != targets.shape[0]:
            raise ValueError(
                "The number of logits and target labels "
                "does not match."
            )

        number_of_classes = logits.shape[-1]

        if torch.any(targets < 0):
            raise ValueError(
                "Targets contain negative class IDs."
            )

        if torch.any(targets >= number_of_classes):
            raise ValueError(
                "A target class ID is larger than the number "
                "of model output classes."
            )

        targets = targets.long()

        log_probabilities = F.log_softmax(
            logits,
            dim=-1,
        )

        log_pt = log_probabilities.gather(
            dim=1,
            index=targets.unsqueeze(1),
        ).squeeze(1)

        pt = log_pt.exp()

        pt = pt.clamp(
            min=0.0,
            max=1.0,
        )

        focal_factor = (
            1.0 - pt
        ).pow(self.gamma)

        per_example_loss = (
            -self.alpha
            * focal_factor
            * log_pt
        )

        if self.reduction == "none":
            return per_example_loss

        if self.reduction == "sum":
            return per_example_loss.sum()

        return per_example_loss.mean()


class FocalTrainer(Trainer):

    def __init__(
        self,
        *args,
        gamma: float = 2.0,
        alpha: float = 1.0,
        **kwargs,
    ):
        super().__init__(
            *args,
            **kwargs,
        )

        self.loss_fn = FocalLoss(
            gamma=gamma,
            alpha=alpha,
            reduction="mean",
        )

        self.model_accepts_loss_kwargs = False

    def compute_loss(
        self,
        model,
        inputs,
        return_outputs=False,
        num_items_in_batch=None,
        **kwargs,
    ):

        model_inputs = dict(inputs)

        labels = model_inputs.pop(
            "labels"
        ).long()

        outputs = model(
            **model_inputs
        )

        logits = outputs.logits

        if logits.shape[-1] != NUM_LABELS:
            raise ValueError(
                f"Expected {NUM_LABELS} model outputs, "
                f"but received {logits.shape[-1]}."
            )

        loss = self.loss_fn(
            logits=logits,
            targets=labels,
        )

        return (
            (loss, outputs)
            if return_outputs
            else loss
        )

In [ ]:
import gc
import json
from transformers import MarianMTModel, MarianTokenizer


def _translate_deterministically(
    texts,
    tokenizer,
    model,
    device,
    batch_size=8,
    max_length=128,
):
    translations = []

    with torch.no_grad():
        for start in range(0, len(texts), batch_size):
            batch = texts[start:start + batch_size]

            encoded = tokenizer(
                batch,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=max_length,
            ).to(device)

            generated = model.generate(
                **encoded,
                max_length=max_length,
                num_beams=4,
                do_sample=False,
            )

            translations.extend(
                tokenizer.batch_decode(
                    generated,
                    skip_special_tokens=True,
                )
            )

    return translations


def _generate_diverse_reverse_translations(
    pivot_texts,
    original_texts,
    tokenizer,
    model,
    device,
    aug_factor=3,
    candidates_per_source=12,
    batch_size=8,
    max_length=128,
    seed=42,
    maximum_attempts=8,
):
    if candidates_per_source < aug_factor:
        raise ValueError(
            "candidates_per_source must be greater than or equal "
            "to aug_factor."
        )

    if maximum_attempts < 1:
        raise ValueError(
            "maximum_attempts must be at least 1."
        )

    selected_paraphrases = []

    temperature_schedule = [
        0.80,
        0.90,
        1.00,
        1.10,
        1.20,
        1.30,
        1.40,
        1.50,
    ]

    top_p_schedule = [
        0.90,
        0.93,
        0.95,
        0.96,
        0.97,
        0.98,
        0.98,
        0.99,
    ]

    with torch.no_grad():
        for start in range(
            0,
            len(pivot_texts),
            batch_size,
        ):
            pivot_batch = pivot_texts[
                start:start + batch_size
            ]

            original_batch = original_texts[
                start:start + batch_size
            ]

            candidate_pools = [
                [] for _ in pivot_batch
            ]

            for attempt in range(maximum_attempts):
                if all(
                    len(pool) >= aug_factor
                    for pool in candidate_pools
                ):
                    break

                current_seed = (
                    seed
                    + start * 100
                    + attempt
                )

                torch.manual_seed(current_seed)

                if torch.cuda.is_available():
                    torch.cuda.manual_seed_all(
                        current_seed
                    )

                temperature = temperature_schedule[
                    min(
                        attempt,
                        len(temperature_schedule) - 1,
                    )
                ]

                top_p = top_p_schedule[
                    min(
                        attempt,
                        len(top_p_schedule) - 1,
                    )
                ]

                encoded = tokenizer(
                    pivot_batch,
                    return_tensors="pt",
                    padding=True,
                    truncation=True,
                    max_length=max_length,
                ).to(device)

                generated = model.generate(
                    **encoded,
                    max_length=max_length,
                    do_sample=True,
                    num_beams=1,
                    top_p=top_p,
                    top_k=50,
                    temperature=temperature,
                    repetition_penalty=1.05,
                    num_return_sequences=(
                        candidates_per_source
                    ),
                )

                decoded = tokenizer.batch_decode(
                    generated,
                    skip_special_tokens=True,
                )

                for local_index, original_text in enumerate(
                    original_batch
                ):
                    if (
                        len(candidate_pools[local_index])
                        >= aug_factor
                    ):
                        continue

                    begin = (
                        local_index
                        * candidates_per_source
                    )

                    end = (
                        begin
                        + candidates_per_source
                    )

                    normalized_original = (
                        " ".join(
                            original_text
                            .strip()
                            .casefold()
                            .split()
                        )
                    )

                    existing_normalized_candidates = {
                        " ".join(
                            existing
                            .strip()
                            .casefold()
                            .split()
                        )
                        for existing
                        in candidate_pools[local_index]
                    }

                    for candidate in decoded[begin:end]:
                        candidate = " ".join(
                            candidate.strip().split()
                        )

                        if not candidate:
                            continue

                        normalized_candidate = (
                            candidate.casefold()
                        )

                        if (
                            normalized_candidate
                            == normalized_original
                        ):
                            continue

                        if (
                            normalized_candidate
                            in existing_normalized_candidates
                        ):
                            continue

                        candidate_pools[
                            local_index
                        ].append(candidate)

                        existing_normalized_candidates.add(
                            normalized_candidate
                        )

                        if (
                            len(
                                candidate_pools[
                                    local_index
                                ]
                            )
                            >= aug_factor
                        ):
                            break

                incomplete_count = sum(
                    len(pool) < aug_factor
                    for pool in candidate_pools
                )

                print(
                    f"Batch beginning at source {start}: "
                    f"attempt {attempt + 1}/"
                    f"{maximum_attempts}; "
                    f"{incomplete_count} sources still "
                    f"need more paraphrases."
                )

            for local_index, pool in enumerate(
                candidate_pools
            ):
                source_index = start + local_index

                if len(pool) < aug_factor:
                    original_text = original_batch[
                        local_index
                    ]

                    raise RuntimeError(
                        "\nUnable to generate enough distinct "
                        "back-translations.\n"
                        f"Source row: {source_index}\n"
                        f"Original text: {original_text!r}\n"
                        f"Distinct paraphrases generated: "
                        f"{len(pool)}\n"
                        f"Required paraphrases: "
                        f"{aug_factor}\n"
                        f"Candidates requested per attempt: "
                        f"{candidates_per_source}\n"
                        f"Attempts: {maximum_attempts}\n\n"
                        "The code stopped rather than inserting "
                        "duplicate or unchanged sentences."
                    )

                selected_paraphrases.append(
                    pool[:aug_factor]
                )

    if len(selected_paraphrases) != len(original_texts):
        raise RuntimeError(
            "The number of generated paraphrase groups does not "
            "match the number of original source texts."
        )

    return selected_paraphrases


def augment_minority_classes(
    train_df,
    top_k=3,
    aug_factor=3,
    candidates_per_source=12,
    maximum_attempts=8,
    pivot="de",
    batch_size=8,
    seed=42,
):

    import gc

    from transformers import (
        MarianMTModel,
        MarianTokenizer,
    )

    required_columns = {
        "text_clean",
        "ekman_id",
    }

    if not required_columns.issubset(
        train_df.columns
    ):
        raise ValueError(
            f"The training dataframe must contain "
            f"{required_columns}."
        )

    class_counts = (
        train_df["ekman_id"]
        .value_counts()
        .sort_values(ascending=True)
    )

    number_of_classes = len(class_counts)

    if not 1 <= top_k < number_of_classes:
        raise ValueError(
            f"top_k must be between 1 and "
            f"{number_of_classes - 1}. "
            f"The dataset contains "
            f"{number_of_classes} classes, "
            f"but top_k={top_k} was requested."
        )

    selected_class_ids = (
        class_counts
        .index[:top_k]
        .astype(int)
        .tolist()
    )

    print("\nOriginal training-class counts:")
    print(
        class_counts
        .sort_index()
        .to_string()
    )

    print(
        f"\nSelected {top_k} rarest classes: "
        f"{selected_class_ids}"
    )

    selected_df = (
        train_df[
            train_df["ekman_id"].isin(
                selected_class_ids
            )
        ]
        .reset_index(drop=True)
        .copy()
    )

    source_texts = (
        selected_df["text_clean"]
        .astype(str)
        .tolist()
    )

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    forward_name = (
        f"Helsinki-NLP/opus-mt-en-{pivot}"
    )

    reverse_name = (
        f"Helsinki-NLP/opus-mt-{pivot}-en"
    )

    print(f"\nLoading {forward_name}...")

    forward_tokenizer = (
        MarianTokenizer.from_pretrained(
            forward_name
        )
    )

    forward_model = (
        MarianMTModel
        .from_pretrained(forward_name)
        .to(device)
        .eval()
    )

    print(
        "Translating English into the pivot "
        "language..."
    )

    pivot_texts = _translate_deterministically(
        texts=source_texts,
        tokenizer=forward_tokenizer,
        model=forward_model,
        device=device,
        batch_size=batch_size,
    )

    del forward_model
    del forward_tokenizer

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    print(f"\nLoading {reverse_name}...")

    reverse_tokenizer = (
        MarianTokenizer.from_pretrained(
            reverse_name
        )
    )

    reverse_model = (
        MarianMTModel
        .from_pretrained(reverse_name)
        .to(device)
        .eval()
    )

    print(
        "Generating diverse English "
        "back-translations..."
    )

    paraphrase_groups = (
        _generate_diverse_reverse_translations(
            pivot_texts=pivot_texts,
            original_texts=source_texts,
            tokenizer=reverse_tokenizer,
            model=reverse_model,
            device=device,
            aug_factor=aug_factor,
            candidates_per_source=(
                candidates_per_source
            ),
            batch_size=batch_size,
            seed=seed,
            maximum_attempts=maximum_attempts,
        )
    )

    extra_rows = []

    for row_index, paraphrases in enumerate(
        paraphrase_groups
    ):
        class_id = int(
            selected_df.iloc[row_index][
                "ekman_id"
            ]
        )

        source_text = source_texts[
            row_index
        ]

        for paraphrase_number, paraphrase in enumerate(
            paraphrases,
            start=1,
        ):
            extra_rows.append({
                "text_clean": paraphrase,
                "ekman_id": class_id,
                "augmentation":
                    "back_translation",
                "source_text": source_text,
                "paraphrase_number":
                    paraphrase_number,
            })

    extra_df = pd.DataFrame(extra_rows)

    expected_examples = (
        len(selected_df) * aug_factor
    )

    if len(extra_df) != expected_examples:
        raise RuntimeError(
            f"Expected {expected_examples} synthetic "
            f"examples, but generated "
            f"{len(extra_df)}."
        )


    augmented_df = train_df.copy()

    augmented_df["augmentation"] = "original"
    augmented_df["source_text"] = (
        augmented_df["text_clean"]
    )
    augmented_df["paraphrase_number"] = 0

    augmented_df = pd.concat(
        [
            augmented_df,
            extra_df,
        ],
        ignore_index=True,
    )

    print(
        f"\nGenerated {len(extra_df):,} "
        f"distinct synthetic examples."
    )

    print("\nAugmented training-class counts:")

    augmented_counts = (
        augmented_df["ekman_id"]
        .value_counts()
        .sort_index()
    )

    print(augmented_counts.to_string())

    augmentation_report = {
        "method": "English-German-English "
                  "back-translation",
        "pivot_language": pivot,
        "diversity_method":
            "top-p sampling during reverse translation",
        "top_k": top_k,
        "aug_factor": aug_factor,
        "candidates_per_source":
            candidates_per_source,
        "maximum_attempts":
            maximum_attempts,
        "selected_class_ids":
            selected_class_ids,
        "original_training_size":
            int(len(train_df)),
        "selected_source_examples":
            int(len(selected_df)),
        "expected_synthetic_examples":
            int(expected_examples),
        "generated_synthetic_examples":
            int(len(extra_df)),
        "augmented_training_size":
            int(len(augmented_df)),
        "original_class_counts": {
            str(int(class_id)): int(count)
            for class_id, count
            in class_counts.sort_index().items()
        },
        "augmented_class_counts": {
            str(int(class_id)): int(count)
            for class_id, count
            in augmented_counts.items()
        },
    }

    del reverse_model
    del reverse_tokenizer

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return (
        augmented_df,
        extra_df,
        augmentation_report,
    )

In [ ]:
from pathlib import Path
from datetime import datetime
import json
import time

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch

from sklearn.metrics import confusion_matrix
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding,
)


def make_json_safe(value):
    if isinstance(value, dict):
        return {
            str(key): make_json_safe(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [make_json_safe(item) for item in value]

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, np.generic):
        return value.item()

    return value


def save_confusion_matrix_to_folder(
    y_true,
    y_pred,
    labels,
    output_path,
    title,
):
    matrix = confusion_matrix(
        y_true,
        y_pred,
        labels=list(range(len(labels))),
    )

    figure, axis = plt.subplots(figsize=(9, 8))

    image = axis.imshow(
        matrix,
        interpolation="nearest",
        cmap="Blues",
    )

    figure.colorbar(image, ax=axis)

    axis.set(
        xticks=np.arange(len(labels)),
        yticks=np.arange(len(labels)),
        xticklabels=labels,
        yticklabels=labels,
        xlabel="Predicted label",
        ylabel="True label",
        title=title,
    )

    plt.setp(
        axis.get_xticklabels(),
        rotation=45,
        ha="right",
        rotation_mode="anchor",
    )

    threshold = matrix.max() / 2 if matrix.size else 0

    for row_index in range(matrix.shape[0]):
        for column_index in range(matrix.shape[1]):
            axis.text(
                column_index,
                row_index,
                format(matrix[row_index, column_index], "d"),
                ha="center",
                va="center",
                color=(
                    "white"
                    if matrix[row_index, column_index] > threshold
                    else "black"
                ),
            )

    figure.tight_layout()
    figure.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(figure)

    return matrix


def run(
    treatment: str,
    seed: int = 42,
    gamma: float = 2.0,
    alpha: float = 1.0,
    top_k: int = 3,
    aug_factor: int = 3,
    candidates_per_source: int = 12,
    maximum_attempts: int = 8,
    output_root=None,
) -> dict:
    set_all_seeds(seed)

    if treatment not in {"cw", "focal", "bt"}:
        raise ValueError(
            "treatment must be 'cw', 'focal', or 'bt'."
        )

    if treatment == "cw":
        basic_run_name = f"phase4_cw_seed{seed}"

    elif treatment == "focal":
        basic_run_name = (
            f"phase4_focal_g{gamma:g}_seed{seed}"
        )

    else:
        basic_run_name = (
            f"phase4_bt_k{top_k}_x{aug_factor}_seed{seed}"
        )

    if output_root is None:
        raise ValueError(
            "You must provide output_root. For example:\n"
            "output_root='/content/drive/MyDrive/Thesis/"
            "corrected_phase4_runs'"
        )

    output_root = Path(output_root)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_name = f"{basic_run_name}_{timestamp}"
    out_dir = output_root / run_name

    if out_dir.exists():
        raise FileExistsError(
            f"The following output folder already exists:\n"
            f"{out_dir}\n"
            "No files were overwritten."
        )

    out_dir.mkdir(
        parents=True,
        exist_ok=False,
    )

    print("=" * 70)
    print("PHASE 4 EXPERIMENT")
    print("=" * 70)
    print(f"Treatment: {treatment}")
    print(f"Seed: {seed}")
    print(f"Run name: {run_name}")
    print(f"All new results will be saved in:\n{out_dir}")
    print("=" * 70)

    train_df, val_df, test_df = load_data()

    original_training_size = len(train_df)

    print("\nOriginal dataset sizes:")
    print(f"Training:   {len(train_df):,}")
    print(f"Validation: {len(val_df):,}")
    print(f"Test:       {len(test_df):,}")

    original_class_counts = (
        train_df["ekman_id"]
        .value_counts()
        .sort_index()
        .to_dict()
    )

    synthetic_df = None
    augmentation_report = None

    if treatment == "bt":
        print("\nStarting P4c back-translation...")
        translation_start_time = time.time()

        (
            train_df,
            synthetic_df,
            augmentation_report,
        ) = augment_minority_classes(
            train_df=train_df,
            top_k=top_k,
            aug_factor=aug_factor,
            candidates_per_source=candidates_per_source,
            maximum_attempts=maximum_attempts,
            pivot="de",
            batch_size=8,
            seed=seed,
        )
        translation_time = (
            time.time() - translation_start_time
        )

        print(
            f"\nBack-translation completed in "
            f"{translation_time:.1f} seconds "
            f"({translation_time / 60:.2f} minutes)."
        )

        synthetic_df.to_csv(
            out_dir / "generated_paraphrases.csv",
            index=False,
        )

        with open(
            out_dir / "augmentation_report.json",
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                make_json_safe(augmentation_report),
                file,
                indent=2,
                ensure_ascii=False,
            )

    else:
        print(
            f"\nNo back-translation applied to "
            f"treatment '{treatment}'."
        )

    final_training_size = len(train_df)

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME
    )

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=NUM_LABELS,
        id2label={
            index: label
            for index, label in enumerate(EKMAN_LABELS)
        },
        label2id={
            label: index
            for index, label in enumerate(EKMAN_LABELS)
        },
    )

    train_ds = GoEmotionsDataset(
        train_df["text_clean"],
        train_df["ekman_id"],
        tokenizer,
    )

    val_ds = GoEmotionsDataset(
        val_df["text_clean"],
        val_df["ekman_id"],
        tokenizer,
    )

    test_ds = GoEmotionsDataset(
        test_df["text_clean"],
        test_df["ekman_id"],
        tokenizer,
    )

    training_args = TrainingArguments(
        output_dir=str(out_dir / "checkpoints"),
        learning_rate=LR,
        weight_decay=WEIGHT_DECAY,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        num_train_epochs=N_EPOCHS,
        warmup_steps=WARMUP,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="macro_f1",
        greater_is_better=True,
        save_total_limit=2,
        logging_steps=100,
        seed=seed,
        data_seed=seed,
        report_to="none",
    )

    common_arguments = dict(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        processing_class=tokenizer,
        data_collator=DataCollatorWithPadding(
            tokenizer=tokenizer
        ),
        compute_metrics=hf_compute_metrics,
    )

    if treatment == "cw":
        weights = compute_class_weights(
            train_df["ekman_id"].values
        )

        print("\nClass weights:")
        for class_index, weight in enumerate(weights.tolist()):
            print(
                f"{EKMAN_LABELS[class_index]}: "
                f"{weight:.6f}"
            )

        trainer = WeightedCETrainer(
            class_weights=weights,
            **common_arguments,
        )

    elif treatment == "focal":
        trainer = FocalTrainer(
            gamma=gamma,
            alpha=alpha,
            **common_arguments,
        )

    else:
        trainer = Trainer(
            **common_arguments
        )

    print("\nStarting training...")

    training_start_time = time.time()

    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()

    train_result = trainer.train()

    training_time = time.time() - training_start_time

    print(
        f"\nTraining completed in {training_time:.1f} seconds "
        f"({training_time / 60:.2f} minutes)."
    )

    peak_gpu_memory_gb = None

    if torch.cuda.is_available():
        peak_gpu_memory_gb = (
            torch.cuda.max_memory_allocated() / 1e9
        )

        print(
            f"Peak training GPU memory: "
            f"{peak_gpu_memory_gb:.2f} GB"
        )

    best_model_dir = out_dir / "best_model"

    trainer.save_model(
        str(best_model_dir)
    )

    tokenizer.save_pretrained(
        str(best_model_dir)
    )

    def evaluate_and_save(
        dataset,
        dataframe,
        split_name,
    ):
        print(f"\nEvaluating {split_name} set...")

        prediction_output = trainer.predict(
            dataset,
            metric_key_prefix=split_name,
        )

        logits = prediction_output.predictions

        if isinstance(logits, tuple):
            logits = logits[0]

        y_true = prediction_output.label_ids.astype(int)
        y_pred = np.argmax(logits, axis=-1).astype(int)

        stable_logits = (
            logits - np.max(logits, axis=1, keepdims=True)
        )

        exponentials = np.exp(stable_logits)

        probabilities = (
            exponentials
            / np.sum(
                exponentials,
                axis=1,
                keepdims=True,
            )
        )

        split_metrics = compute_metrics(
            y_true,
            y_pred,
            EKMAN_LABELS,
        )

        predictions_dataframe = pd.DataFrame({
            "id": dataframe["id"].tolist(),
            "text_clean": dataframe[
                "text_clean"
            ].astype(str).tolist(),
            "true_id": y_true,
            "true_label": [
                EKMAN_LABELS[value]
                for value in y_true
            ],
            "predicted_id": y_pred,
            "predicted_label": [
                EKMAN_LABELS[value]
                for value in y_pred
            ],
            "correct": y_true == y_pred,
        })

        for class_index, class_name in enumerate(
            EKMAN_LABELS
        ):
            safe_class_name = (
                str(class_name)
                .lower()
                .replace(" ", "_")
            )

            predictions_dataframe[
                f"probability_{safe_class_name}"
            ] = probabilities[:, class_index]

        predictions_dataframe.to_csv(
            out_dir / f"{split_name}_predictions.csv",
            index=False,
        )

        confusion_matrix_values = (
            save_confusion_matrix_to_folder(
                y_true=y_true,
                y_pred=y_pred,
                labels=EKMAN_LABELS,
                output_path=(
                    out_dir
                    / f"{split_name}_confusion_matrix.png"
                ),
                title=(
                    f"{split_name.capitalize()} confusion matrix"
                ),
            )
        )

        np.savetxt(
            out_dir
            / f"{split_name}_confusion_matrix.csv",
            confusion_matrix_values,
            delimiter=",",
            fmt="%d",
        )

        with open(
            out_dir / f"{split_name}_metrics.json",
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                make_json_safe(split_metrics),
                file,
                indent=2,
                ensure_ascii=False,
            )

        return split_metrics

    validation_metrics = evaluate_and_save(
        dataset=val_ds,
        dataframe=val_df,
        split_name="validation",
    )

    test_metrics = evaluate_and_save(
        dataset=test_ds,
        dataframe=test_df,
        split_name="test",
    )

    final_class_counts = (
        train_df["ekman_id"]
        .value_counts()
        .sort_index()
        .to_dict()
    )

    complete_results = {
        "run_name": run_name,
        "treatment": treatment,
        "seed": seed,
        "model_name": MODEL_NAME,
        "top_k": top_k if treatment == "bt" else None,
        "augmentation_factor": (
            aug_factor if treatment == "bt" else None
        ),
        "candidates_per_source": (
            candidates_per_source
            if treatment == "bt"
            else None
        ),
        "gamma": (
            gamma if treatment == "focal" else None
        ),
        "alpha": (
            alpha if treatment == "focal" else None
        ),
        "original_training_size":
            original_training_size,
        "final_training_size":
            final_training_size,
        "original_training_class_counts":
            original_class_counts,
        "final_training_class_counts":
            final_class_counts,
        "best_checkpoint":
            trainer.state.best_model_checkpoint,
        "best_validation_macro_f1_during_training":
            trainer.state.best_metric,
        "training_time_seconds":
            training_time,
        "peak_gpu_memory_gb":
            peak_gpu_memory_gb,
        "augmentation":
            augmentation_report,
        "validation":
            validation_metrics,
        "test":
            test_metrics,
    }

    complete_results_path = (
        out_dir / "complete_results.json"
    )

    with open(
        complete_results_path,
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            make_json_safe(complete_results),
            file,
            indent=2,
            ensure_ascii=False,
        )

    with open(
        out_dir / "training_log_history.json",
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            make_json_safe(trainer.state.log_history),
            file,
            indent=2,
            ensure_ascii=False,
        )

    print("\n" + "=" * 70)
    print("FINAL RESULTS")
    print("=" * 70)

    print("\nValidation metrics:")
    print(
        json.dumps(
            make_json_safe(validation_metrics),
            indent=2,
        )
    )

    print("\nTest metrics:")
    print(
        json.dumps(
            make_json_safe(test_metrics),
            indent=2,
        )
    )

    print(f"\nBest checkpoint:")
    print(trainer.state.best_model_checkpoint)

    print("\nAll results were saved in:")
    print(out_dir)

    print("\nNo original dataset files were modified.")
    print("=" * 70)

    return complete_results

In [ ]:
P4C_OUTPUT_LOCATION = (
    "/content/drive/MyDrive/Thesis/models_new"
)

p4c_results = run(
    treatment="bt",
    seed=42,
    top_k=3,
    aug_factor=3,
    candidates_per_source=12,
    maximum_attempts=8,
    output_root=P4C_OUTPUT_LOCATION,
)

======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: bt
Seed: 42
Run name: phase4_bt_k3_x3_seed42_20260619_100401
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_bt_k3_x3_seed42_20260619_100401
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Starting P4c back-translation...

Original training-class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Selected 3 rarest classes: [1, 2, 4]

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Translating English into the pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Generating diverse English back-translations...
Batch beginning at source 0: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 0: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 8: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 16: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 16: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 16: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 24: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 24: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 24: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 32: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 40: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 48: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 56: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 64: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 72: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 80: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 80: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 80: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 88: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 88: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 96: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 96: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 104: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 104: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 112: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 120: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 120: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 128: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 128: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 136: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 136: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 144: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 144: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 152: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 160: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 160: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 160: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 168: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 176: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 184: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 192: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 200: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 200: attempt 2/8; 2 sources still need more paraphrases.
Batch beginning at source 200: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 208: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 216: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 224: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 232: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 232: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 232: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 232: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 240: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 248: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 256: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 264: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 264: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 272: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 280: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 280: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 288: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 288: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 296: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 296: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 304: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 304: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 312: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 312: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 320: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 320: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 328: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 328: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 336: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 344: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 344: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 344: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 352: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 352: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 360: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 368: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 376: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 376: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 376: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 384: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 384: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 384: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 384: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 392: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 392: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 392: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 400: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 400: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 408: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 408: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 408: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 416: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 416: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 416: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 424: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 424: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 432: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 432: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 432: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 440: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 440: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 448: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 456: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 456: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 456: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 464: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 464: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 464: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 472: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 480: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 480: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 488: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 496: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 504: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 512: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 520: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 528: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 528: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 528: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 536: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 544: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 552: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 560: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 560: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 568: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 576: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 576: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 584: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 592: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 592: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 600: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 608: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 608: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 608: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 616: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 616: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 624: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 632: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 632: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 640: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 648: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 648: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 648: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 656: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 664: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 664: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 664: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 672: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 680: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 688: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 688: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 688: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 696: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 696: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 696: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 704: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 704: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 712: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 712: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 720: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 728: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 736: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 744: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 752: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 760: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 760: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 768: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 768: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 776: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 784: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 784: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 792: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 792: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 800: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 808: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 816: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 824: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 832: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 840: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 848: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 856: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 864: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 864: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 872: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 872: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 880: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 888: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 888: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 896: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 896: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 904: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 912: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 912: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 912: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 920: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 928: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 936: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 936: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 944: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 952: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 952: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 952: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 952: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 960: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 960: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 968: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 976: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 976: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 984: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 992: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 992: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 1000: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 1000: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 1000: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 1008: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 1008: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 1016: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1024: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1032: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1040: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 1040: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 1040: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 1048: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1056: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1064: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 1064: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 1072: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1080: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1088: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1096: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 1096: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 1096: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 1104: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 1104: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 1112: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 1112: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 1120: attempt 1/8; 0 sources still need more paraphrases.

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 525.7 seconds (8.76 minutes).
Peak training GPU memory: 2.18 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.686826478997141,
  "macro_f1": 0.5980211106599319,
  "weighted_f1": 0.6859895758851762,
  "per_class_f1": [
    0.45614035087719296,
    0.45348837209302323,
    0.6356589147286822,
    0.8065635847270433,
    0.5730337078651685,
    0.572463768115942,
    0.6887990762124712
  ],
  "report": {
    "anger": {
      "precision": 0.5814696485623003,
      "recall": 0.3752577319587629,
      "f1-score": 0.45614035087719296,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.35135135135135137,
      "recall": 0.639344262295082,
      "f1-score": 0.45348837209302323,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6507936507936508,
      "recall": 0.6212121212121212,
      "f1-score": 0.6356589147286822,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8514323784143905,
      "recall": 0.7661870503597122,
      "f1-score": 0.8065635847270433,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5221843003412969,
      "recall": 0.6348547717842323,
      "f1-score": 0.5730337078651685,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.6030534351145038,
      "recall": 0.5448275862068965,
      "f1-score": 0.572463768115942,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6369460758142018,
      "recall": 0.7498428661219358,
      "f1-score": 0.6887990762124712,
      "support": 1591.0
    },
    "accuracy": 0.686826478997141,
    "macro avg": {
      "precision": 0.5996044057702423,
      "recall": 0.6187894842769632,
      "f1-score": 0.5980211106599319,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6967544903035384,
      "recall": 0.686826478997141,
      "f1-score": 0.6859895758851762,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6801742919389978,
  "macro_f1": 0.601451081592887,
  "weighted_f1": 0.6791351190286173,
  "per_class_f1": [
    0.4722222222222222,
    0.4816753926701571,
    0.6329113924050633,
    0.8045901639344263,
    0.5869565217391305,
    0.5477272727272727,
    0.6840746054519369
  ],
  "report": {
    "anger": {
      "precision": 0.5930232558139535,
      "recall": 0.3923076923076923,
      "f1-score": 0.4722222222222222,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.4,
      "recall": 0.6052631578947368,
      "f1-score": 0.4816753926701571,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6172839506172839,
      "recall": 0.6493506493506493,
      "f1-score": 0.6329113924050633,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8479612992398065,
      "recall": 0.7654398003742982,
      "f1-score": 0.8045901639344263,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.552901023890785,
      "recall": 0.6254826254826255,
      "f1-score": 0.5869565217391305,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5591647331786543,
      "recall": 0.5367483296213809,
      "f1-score": 0.5477272727272727,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6343799893560405,
      "recall": 0.7422166874221668,
      "f1-score": 0.6840746054519369,
      "support": 1606.0
    },
    "accuracy": 0.6801742919389978,
    "macro avg": {
      "precision": 0.6006734645852176,
      "recall": 0.6166869917790787,
      "f1-score": 0.601451081592887,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6881624211749295,
      "recall": 0.6801742919389978,
      "f1-score": 0.6791351190286173,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_bt_k3_x3_seed42_20260619_100401/checkpoints/checkpoint-1429

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_bt_k3_x3_seed42_20260619_100401

No original dataset files were modified.
======================================================================

In [ ]:
P4C_OUTPUT_LOCATION = (
    "/content/drive/MyDrive/Thesis/models_new"
)

p4c_seed_0_results = run(
    treatment="bt",
    seed=0,
    top_k=3,
    aug_factor=3,
    candidates_per_source=12,
    maximum_attempts=8,
    output_root=P4C_OUTPUT_LOCATION,
)

p4c_seed_1_results = run(
    treatment="bt",
    seed=1,
    top_k=3,
    aug_factor=3,
    candidates_per_source=12,
    maximum_attempts=8,
    output_root=P4C_OUTPUT_LOCATION,
)

======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: bt
Seed: 0
Run name: phase4_bt_k3_x3_seed0_20260619_114814
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_bt_k3_x3_seed0_20260619_114814
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Starting P4c back-translation...

Original training-class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Selected 3 rarest classes: [1, 2, 4]

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

source.spm:   0%|          | 0.00/768k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/797k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

config.json:   0%|          | 0.00/1.33k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/298M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/298M [00:00<?, ?B/s]

Translating English into the pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/797k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/768k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/298M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

Generating diverse English back-translations...

model.safetensors:   0%|          | 0.00/298M [00:00<?, ?B/s]

Batch beginning at source 0: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 0: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 8: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 16: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 16: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 24: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 24: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 32: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 40: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 48: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 56: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 56: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 64: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 64: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 72: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 80: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 80: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 88: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 88: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 96: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 104: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 104: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 112: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 120: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 120: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 128: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 128: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 136: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 136: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 144: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 144: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 144: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 152: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 160: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 160: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 168: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 176: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 184: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 192: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 192: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 200: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 200: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 200: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 208: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 216: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 224: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 232: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 232: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 232: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 232: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 240: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 248: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 248: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 248: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 256: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 264: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 264: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 264: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 272: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 280: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 280: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 280: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 288: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 288: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 296: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 296: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 304: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 304: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 304: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 304: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 312: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 312: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 320: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 320: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 328: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 328: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 328: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 328: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 336: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 344: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 344: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 344: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 352: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 352: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 360: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 360: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 368: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 376: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 376: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 384: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 384: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 384: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 384: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 392: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 392: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 392: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 400: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 400: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 408: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 408: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 408: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 416: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 416: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 424: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 424: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 432: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 432: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 432: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 440: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 440: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 448: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 456: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 456: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 456: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 464: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 464: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 464: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 464: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 472: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 480: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 480: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 488: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 488: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 496: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 504: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 512: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 520: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 528: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 528: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 528: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 536: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 536: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 544: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 552: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 560: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 560: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 568: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 576: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 576: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 576: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 584: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 592: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 592: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 600: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 608: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 608: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 608: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 608: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 616: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 616: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 616: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 624: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 624: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 632: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 632: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 632: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 640: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 648: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 648: attempt 2/8; 2 sources still need more paraphrases.
Batch beginning at source 648: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 648: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 656: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 664: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 664: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 664: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 672: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 680: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 688: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 688: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 688: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 696: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 696: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 696: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 704: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 704: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 712: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 712: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 720: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 728: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 736: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 744: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 752: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 760: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 768: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 768: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 776: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 776: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 784: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 784: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 792: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 792: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 800: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 800: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 808: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 816: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 824: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 832: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 840: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 840: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 848: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 856: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 864: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 864: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 872: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 880: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 888: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 888: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 888: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 896: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 896: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 896: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 904: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 912: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 912: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 912: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 920: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 928: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 936: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 936: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 944: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 952: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 952: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 952: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 952: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 960: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 960: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 960: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 968: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 976: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 976: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 984: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 992: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 992: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 1000: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 1000: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 1008: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 1008: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 1016: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1024: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1032: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1040: attempt 1/8; 1 sources still need more paraphrases.

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 485.3 seconds (8.09 minutes).
Peak training GPU memory: 2.18 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.6791290961073235,
  "macro_f1": 0.5971106815131514,
  "weighted_f1": 0.6811833661927383,
  "per_class_f1": [
    0.47029702970297027,
    0.4550898203592814,
    0.6388888888888888,
    0.8080301129234629,
    0.565359477124183,
    0.5717321997874601,
    0.6703772418058133
  ],
  "report": {
    "anger": {
      "precision": 0.5882352941176471,
      "recall": 0.3917525773195876,
      "f1-score": 0.47029702970297027,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.3584905660377358,
      "recall": 0.6229508196721312,
      "f1-score": 0.4550898203592814,
      "support": 61.0
    },
    "fear": {
      "precision": 0.5897435897435898,
      "recall": 0.696969696969697,
      "f1-score": 0.6388888888888888,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8473684210526315,
      "recall": 0.7721822541966427,
      "f1-score": 0.8080301129234629,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.46630727762803237,
      "recall": 0.7178423236514523,
      "f1-score": 0.565359477124183,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5316205533596838,
      "recall": 0.6183908045977011,
      "f1-score": 0.5717321997874601,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6597687157638467,
      "recall": 0.6813324952859836,
      "f1-score": 0.6703772418058133,
      "support": 1591.0
    },
    "accuracy": 0.6791290961073235,
    "macro avg": {
      "precision": 0.5773620596718809,
      "recall": 0.6430601388133137,
      "f1-score": 0.5971106815131514,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6933852357190071,
      "recall": 0.6791290961073235,
      "f1-score": 0.6811833661927383,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6747276688453159,
  "macro_f1": 0.6041965472649997,
  "weighted_f1": 0.6762905972768083,
  "per_class_f1": [
    0.4818181818181818,
    0.4945054945054945,
    0.6470588235294118,
    0.807381029459372,
    0.5564387917329093,
    0.5765407554671969,
    0.6656327543424317
  ],
  "report": {
    "anger": {
      "precision": 0.5888888888888889,
      "recall": 0.4076923076923077,
      "f1-score": 0.4818181818181818,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.42452830188679247,
      "recall": 0.5921052631578947,
      "f1-score": 0.4945054945054945,
      "support": 76.0
    },
    "fear": {
      "precision": 0.5913978494623656,
      "recall": 0.7142857142857143,
      "f1-score": 0.6470588235294118,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8391655450874832,
      "recall": 0.7779164067373674,
      "f1-score": 0.807381029459372,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.47297297297297297,
      "recall": 0.6756756756756757,
      "f1-score": 0.5564387917329093,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5206463195691203,
      "recall": 0.6458797327394209,
      "f1-score": 0.5765407554671969,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6631644004944376,
      "recall": 0.6681195516811955,
      "f1-score": 0.6656327543424317,
      "support": 1606.0
    },
    "accuracy": 0.6747276688453159,
    "macro avg": {
      "precision": 0.5858234683374371,
      "recall": 0.6402392359956537,
      "f1-score": 0.6041965472649997,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6863874947777904,
      "recall": 0.6747276688453159,
      "f1-score": 0.6762905972768083,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_bt_k3_x3_seed0_20260619_114814/checkpoints/checkpoint-1429

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_bt_k3_x3_seed0_20260619_114814

No original dataset files were modified.
======================================================================
======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: bt
Seed: 1
Run name: phase4_bt_k3_x3_seed1_20260619_120714
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_bt_k3_x3_seed1_20260619_120714
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

Starting P4c back-translation...

Original training-class counts:
ekman_id
0     3878
1      497
2      515
3    12920
4     2121
5     3553
6    12818

Selected 3 rarest classes: [1, 2, 4]

Loading Helsinki-NLP/opus-mt-en-de...

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Translating English into the pivot language...

Loading Helsinki-NLP/opus-mt-de-en...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Generating diverse English back-translations...
Batch beginning at source 0: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 0: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 8: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 16: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 16: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 16: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 24: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 24: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 32: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 40: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 48: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 56: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 56: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 64: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 72: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 80: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 80: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 80: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 88: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 88: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 88: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 96: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 104: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 104: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 112: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 120: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 120: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 128: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 128: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 136: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 136: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 144: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 144: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 144: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 152: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 152: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 160: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 160: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 168: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 176: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 176: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 184: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 192: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 192: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 200: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 200: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 200: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 208: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 216: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 224: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 232: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 232: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 232: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 232: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 240: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 248: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 248: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 256: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 256: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 264: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 264: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 264: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 272: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 280: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 280: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 288: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 288: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 296: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 296: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 304: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 304: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 304: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 312: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 312: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 320: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 328: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 328: attempt 2/8; 2 sources still need more paraphrases.
Batch beginning at source 328: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 336: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 336: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 344: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 344: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 352: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 352: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 360: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 368: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 376: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 376: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 384: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 384: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 384: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 384: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 392: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 392: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 400: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 400: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 408: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 408: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 408: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 416: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 416: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 416: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 424: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 424: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 432: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 432: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 432: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 440: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 440: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 440: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 448: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 456: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 456: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 456: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 464: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 464: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 464: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 472: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 480: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 480: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 488: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 496: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 504: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 512: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 520: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 528: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 528: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 536: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 544: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 552: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 560: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 560: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 568: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 576: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 576: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 576: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 584: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 592: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 592: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 592: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 600: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 600: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 608: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 608: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 608: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 616: attempt 1/8; 3 sources still need more paraphrases.
Batch beginning at source 616: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 624: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 632: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 632: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 632: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 640: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 648: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 648: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 648: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 648: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 656: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 664: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 664: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 664: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 664: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 672: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 680: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 688: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 688: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 688: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 688: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 696: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 696: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 696: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 704: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 712: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 712: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 720: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 728: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 736: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 744: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 752: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 760: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 768: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 768: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 776: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 784: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 784: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 792: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 792: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 800: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 808: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 816: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 816: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 824: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 832: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 840: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 840: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 848: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 856: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 864: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 864: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 872: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 880: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 888: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 888: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 896: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 896: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 896: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 896: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 904: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 912: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 912: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 912: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 920: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 928: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 936: attempt 1/8; 2 sources still need more paraphrases.
Batch beginning at source 936: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 936: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 944: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 952: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 952: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 952: attempt 3/8; 1 sources still need more paraphrases.
Batch beginning at source 952: attempt 4/8; 0 sources still need more paraphrases.
Batch beginning at source 960: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 960: attempt 2/8; 1 sources still need more paraphrases.
Batch beginning at source 960: attempt 3/8; 0 sources still need more paraphrases.
Batch beginning at source 968: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 976: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 976: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 984: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 992: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1000: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 1000: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 1008: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1016: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1024: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 1024: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 1032: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1040: attempt 1/8; 1 sources still need more paraphrases.
Batch beginning at source 1040: attempt 2/8; 0 sources still need more paraphrases.
Batch beginning at source 1048: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1056: attempt 1/8; 0 sources still need more paraphrases.
Batch beginning at source 1064: attempt 1/8; 2 sources still need more paraphrases.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 488.0 seconds (8.13 minutes).
Peak training GPU memory: 2.18 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.6659335825819221,
  "macro_f1": 0.5872452781985764,
  "weighted_f1": 0.6733496569535082,
  "per_class_f1": [
    0.47297297297297297,
    0.430939226519337,
    0.6762589928057554,
    0.8040907638223075,
    0.4930747922437673,
    0.5717592592592593,
    0.6616209397666352
  ],
  "report": {
    "anger": {
      "precision": 0.5210918114143921,
      "recall": 0.4329896907216495,
      "f1-score": 0.47297297297297297,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.325,
      "recall": 0.639344262295082,
      "f1-score": 0.430939226519337,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6438356164383562,
      "recall": 0.7121212121212122,
      "f1-score": 0.6762589928057554,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8610540725530459,
      "recall": 0.7541966426858513,
      "f1-score": 0.8040907638223075,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.3700623700623701,
      "recall": 0.7385892116182573,
      "f1-score": 0.4930747922437673,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5757575757575758,
      "recall": 0.5678160919540229,
      "f1-score": 0.5717592592592593,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6639240506329114,
      "recall": 0.6593337523570082,
      "f1-score": 0.6616209397666352,
      "support": 1591.0
    },
    "accuracy": 0.6659335825819221,
    "macro avg": {
      "precision": 0.5658179281226644,
      "recall": 0.6434844091075833,
      "f1-score": 0.5872452781985764,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6921549622687334,
      "recall": 0.6659335825819221,
      "f1-score": 0.6733496569535082,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6679738562091503,
  "macro_f1": 0.6021014620512297,
  "weighted_f1": 0.6736099998072906,
  "per_class_f1": [
    0.4780278670953912,
    0.494949494949495,
    0.6875,
    0.8084684088653655,
    0.5040431266846361,
    0.5773420479302832,
    0.6643792888334373
  ],
  "report": {
    "anger": {
      "precision": 0.5399515738498789,
      "recall": 0.4288461538461538,
      "f1-score": 0.4780278670953912,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.4016393442622951,
      "recall": 0.6447368421052632,
      "f1-score": 0.494949494949495,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6626506024096386,
      "recall": 0.7142857142857143,
      "f1-score": 0.6875,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8605633802816901,
      "recall": 0.7623206487835309,
      "f1-score": 0.8084684088653655,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.38716356107660455,
      "recall": 0.722007722007722,
      "f1-score": 0.5040431266846361,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5650319829424307,
      "recall": 0.5902004454342984,
      "f1-score": 0.5773420479302832,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.665625,
      "recall": 0.6631382316313823,
      "f1-score": 0.6643792888334373,
      "support": 1606.0
    },
    "accuracy": 0.6679738562091503,
    "macro avg": {
      "precision": 0.5832322064032197,
      "recall": 0.6465051082991522,
      "f1-score": 0.6021014620512297,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6894934806542385,
      "recall": 0.6679738562091503,
      "f1-score": 0.6736099998072906,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_bt_k3_x3_seed1_20260619_120714/checkpoints/checkpoint-1429

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_bt_k3_x3_seed1_20260619_120714

No original dataset files were modified.
======================================================================

In [ ]:
P4A_OUTPUT_LOCATION = (
  "/content/drive/MyDrive/Thesis/models_new"
)

p4a_seed_42_results = run(
    treatment="cw",
    seed=42,
    output_root=P4A_OUTPUT_LOCATION,
)

p4a_seed_0_results = run(
    treatment="cw",
    seed=0,
    output_root=P4A_OUTPUT_LOCATION,
)

p4a_seed_1_results = run(
    treatment="cw",
    seed=1,
    output_root=P4A_OUTPUT_LOCATION,
)

======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: cw
Seed: 42
Run name: phase4_cw_seed42_20260619_131809
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_cw_seed42_20260619_131809
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

No back-translation applied to treatment 'cw'.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Training class counts:
0: anger      count=3878   weight=1.337287
1: disgust    count=497    weight=10.434608
2: fear       count=515    weight=10.069903
3: joy        count=12920  weight=0.401393
4: sadness    count=2121   weight=2.445073
5: surprise   count=3553   weight=1.459612
6: neutral    count=12818  weight=0.404587

Class weights:
anger: 1.337287
disgust: 10.434608
fear: 10.069903
joy: 0.401393
sadness: 2.445073
surprise: 1.459612
neutral: 0.404587

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 394.0 seconds (6.57 minutes).
Peak training GPU memory: 3.19 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.664614031229382,
  "macro_f1": 0.6010893366808332,
  "weighted_f1": 0.672570123879129,
  "per_class_f1": [
    0.5379310344827586,
    0.4431137724550898,
    0.6171428571428571,
    0.8024219247928617,
    0.604735883424408,
    0.5774134790528234,
    0.6248664054150338
  ],
  "report": {
    "anger": {
      "precision": 0.4622222222222222,
      "recall": 0.643298969072165,
      "f1-score": 0.5379310344827586,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.3490566037735849,
      "recall": 0.6065573770491803,
      "f1-score": 0.4431137724550898,
      "support": 61.0
    },
    "fear": {
      "precision": 0.4954128440366973,
      "recall": 0.8181818181818182,
      "f1-score": 0.6171428571428571,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8564625850340136,
      "recall": 0.7547961630695443,
      "f1-score": 0.8024219247928617,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.538961038961039,
      "recall": 0.6887966804979253,
      "f1-score": 0.604735883424408,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.4781297134238311,
      "recall": 0.728735632183908,
      "f1-score": 0.5774134790528234,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.7212171052631579,
      "recall": 0.5512256442489001,
      "f1-score": 0.6248664054150338,
      "support": 1591.0
    },
    "accuracy": 0.664614031229382,
    "macro avg": {
      "precision": 0.5573517303877923,
      "recall": 0.6845131834719203,
      "f1-score": 0.6010893366808332,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.7020188080830844,
      "recall": 0.664614031229382,
      "f1-score": 0.672570123879129,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6549019607843137,
  "macro_f1": 0.6086562447422031,
  "weighted_f1": 0.6616748587132435,
  "per_class_f1": [
    0.5327868852459017,
    0.5221674876847291,
    0.6261682242990654,
    0.8011869436201781,
    0.604982206405694,
    0.5645438898450946,
    0.6087580760947595
  ],
  "report": {
    "anger": {
      "precision": 0.4642857142857143,
      "recall": 0.625,
      "f1-score": 0.5327868852459017,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.41732283464566927,
      "recall": 0.6973684210526315,
      "f1-score": 0.5221674876847291,
      "support": 76.0
    },
    "fear": {
      "precision": 0.48905109489051096,
      "recall": 0.8701298701298701,
      "f1-score": 0.6261682242990654,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8496503496503497,
      "recall": 0.7579538365564567,
      "f1-score": 0.8011869436201781,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5610561056105611,
      "recall": 0.6563706563706564,
      "f1-score": 0.604982206405694,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.4600280504908836,
      "recall": 0.7305122494432071,
      "f1-score": 0.5645438898450946,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.7186440677966102,
      "recall": 0.5280199252801993,
      "f1-score": 0.6087580760947595,
      "support": 1606.0
    },
    "accuracy": 0.6549019607843137,
    "macro avg": {
      "precision": 0.5657197453386142,
      "recall": 0.6950507084047174,
      "f1-score": 0.6086562447422031,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6925490306236645,
      "recall": 0.6549019607843137,
      "f1-score": 0.6616748587132435,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_cw_seed42_20260619_131809/checkpoints/checkpoint-2270

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_cw_seed42_20260619_131809

No original dataset files were modified.
======================================================================
======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: cw
Seed: 0
Run name: phase4_cw_seed0_20260619_132502
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_cw_seed0_20260619_132502
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

No back-translation applied to treatment 'cw'.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Training class counts:
0: anger      count=3878   weight=1.337287
1: disgust    count=497    weight=10.434608
2: fear       count=515    weight=10.069903
3: joy        count=12920  weight=0.401393
4: sadness    count=2121   weight=2.445073
5: surprise   count=3553   weight=1.459612
6: neutral    count=12818  weight=0.404587

Class weights:
anger: 1.337287
disgust: 10.434608
fear: 10.069903
joy: 0.401393
sadness: 2.445073
surprise: 1.459612
neutral: 0.404587

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 394.4 seconds (6.57 minutes).
Peak training GPU memory: 3.20 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.6529579942819441,
  "macro_f1": 0.5908893256985769,
  "weighted_f1": 0.6625162099661227,
  "per_class_f1": [
    0.5173247381144238,
    0.43956043956043955,
    0.5876288659793815,
    0.7931590835753469,
    0.6037037037037037,
    0.5826330532212886,
    0.6122153957354536
  ],
  "report": {
    "anger": {
      "precision": 0.4246031746031746,
      "recall": 0.6618556701030928,
      "f1-score": 0.5173247381144238,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.3305785123966942,
      "recall": 0.6557377049180327,
      "f1-score": 0.43956043956043955,
      "support": 61.0
    },
    "fear": {
      "precision": 0.4453125,
      "recall": 0.8636363636363636,
      "f1-score": 0.5876288659793815,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8588399720475192,
      "recall": 0.736810551558753,
      "f1-score": 0.7931590835753469,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5451505016722408,
      "recall": 0.6763485477178424,
      "f1-score": 0.6037037037037037,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.49056603773584906,
      "recall": 0.7172413793103448,
      "f1-score": 0.5826330532212886,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.7202380952380952,
      "recall": 0.5323695788812068,
      "f1-score": 0.6122153957354536,
      "support": 1591.0
    },
    "accuracy": 0.6529579942819441,
    "macro avg": {
      "precision": 0.545041256241939,
      "recall": 0.6919999708750908,
      "f1-score": 0.5908893256985769,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6990784768321782,
      "recall": 0.6529579942819441,
      "f1-score": 0.6625162099661227,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6427015250544662,
  "macro_f1": 0.5898121855893917,
  "weighted_f1": 0.6512750338700047,
  "per_class_f1": [
    0.5231010180109632,
    0.509090909090909,
    0.5617021276595745,
    0.7973154362416107,
    0.5784832451499118,
    0.5651408450704225,
    0.5938517179023508
  ],
  "report": {
    "anger": {
      "precision": 0.44121532364597094,
      "recall": 0.6423076923076924,
      "f1-score": 0.5231010180109632,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.3888888888888889,
      "recall": 0.7368421052631579,
      "f1-score": 0.509090909090909,
      "support": 76.0
    },
    "fear": {
      "precision": 0.4177215189873418,
      "recall": 0.8571428571428571,
      "f1-score": 0.5617021276595745,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8627450980392157,
      "recall": 0.7411104179663132,
      "f1-score": 0.7973154362416107,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.5324675324675324,
      "recall": 0.6332046332046332,
      "f1-score": 0.5784832451499118,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.4672489082969432,
      "recall": 0.7149220489977728,
      "f1-score": 0.5651408450704225,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.7083692838654012,
      "recall": 0.5112079701120797,
      "f1-score": 0.5938517179023508,
      "support": 1606.0
    },
    "accuracy": 0.6427015250544662,
    "macro avg": {
      "precision": 0.5455223648844706,
      "recall": 0.6909625321420724,
      "f1-score": 0.5898121855893917,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6883393014362966,
      "recall": 0.6427015250544662,
      "f1-score": 0.6512750338700047,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_cw_seed0_20260619_132502/checkpoints/checkpoint-2270

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_cw_seed0_20260619_132502

No original dataset files were modified.
======================================================================
======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: cw
Seed: 1
Run name: phase4_cw_seed1_20260619_133153
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_cw_seed1_20260619_133153
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

No back-translation applied to treatment 'cw'.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Training class counts:
0: anger      count=3878   weight=1.337287
1: disgust    count=497    weight=10.434608
2: fear       count=515    weight=10.069903
3: joy        count=12920  weight=0.401393
4: sadness    count=2121   weight=2.445073
5: surprise   count=3553   weight=1.459612
6: neutral    count=12818  weight=0.404587

Class weights:
anger: 1.337287
disgust: 10.434608
fear: 10.069903
joy: 0.401393
sadness: 2.445073
surprise: 1.459612
neutral: 0.404587

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 399.9 seconds (6.66 minutes).
Peak training GPU memory: 3.19 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.6632944798768419,
  "macro_f1": 0.6034143653534988,
  "weighted_f1": 0.6694198230236954,
  "per_class_f1": [
    0.5283993115318416,
    0.45454545454545453,
    0.6459627329192547,
    0.8072251635004671,
    0.5916955017301038,
    0.5837231057062675,
    0.6123492875411034
  ],
  "report": {
    "anger": {
      "precision": 0.4534711964549483,
      "recall": 0.6329896907216495,
      "f1-score": 0.5283993115318416,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.34782608695652173,
      "recall": 0.6557377049180327,
      "f1-score": 0.45454545454545453,
      "support": 61.0
    },
    "fear": {
      "precision": 0.5473684210526316,
      "recall": 0.7878787878787878,
      "f1-score": 0.6459627329192547,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8399222294232016,
      "recall": 0.7769784172661871,
      "f1-score": 0.8072251635004671,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.5074183976261127,
      "recall": 0.7095435684647303,
      "f1-score": 0.5916955017301038,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.4921135646687697,
      "recall": 0.7172413793103448,
      "f1-score": 0.5837231057062675,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.731239092495637,
      "recall": 0.5267127592708988,
      "f1-score": 0.6123492875411034,
      "support": 1591.0
    },
    "accuracy": 0.6632944798768419,
    "macro avg": {
      "precision": 0.5599084269539747,
      "recall": 0.6867260439758044,
      "f1-score": 0.6034143653534988,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6989281167081017,
      "recall": 0.6632944798768419,
      "f1-score": 0.6694198230236954,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6490196078431373,
  "macro_f1": 0.5991420879964686,
  "weighted_f1": 0.6536044299599038,
  "per_class_f1": [
    0.5138662316476346,
    0.52,
    0.6206896551724138,
    0.8078280397818415,
    0.5756578947368421,
    0.5661047027506655,
    0.5898480918858836
  ],
  "report": {
    "anger": {
      "precision": 0.4461756373937677,
      "recall": 0.6057692307692307,
      "f1-score": 0.5138662316476346,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.41935483870967744,
      "recall": 0.6842105263157895,
      "f1-score": 0.52,
      "support": 76.0
    },
    "fear": {
      "precision": 0.5,
      "recall": 0.8181818181818182,
      "f1-score": 0.6206896551724138,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8315719947159842,
      "recall": 0.785402370555209,
      "f1-score": 0.8078280397818415,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.501432664756447,
      "recall": 0.6756756756756757,
      "f1-score": 0.5756578947368421,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.47050147492625366,
      "recall": 0.7104677060133631,
      "f1-score": 0.5661047027506655,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.7282708142726441,
      "recall": 0.49564134495641343,
      "f1-score": 0.5898480918858836,
      "support": 1606.0
    },
    "accuracy": 0.6490196078431373,
    "macro avg": {
      "precision": 0.5567582035392534,
      "recall": 0.6821926674953571,
      "f1-score": 0.5991420879964686,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6854294895102595,
      "recall": 0.6490196078431373,
      "f1-score": 0.6536044299599038,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_cw_seed1_20260619_133153/checkpoints/checkpoint-3405

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_cw_seed1_20260619_133153

No original dataset files were modified.
======================================================================

In [ ]:
P4B_GAMMA2_OUTPUT_LOCATION = (
        "/content/drive/MyDrive/Thesis/models_new"
)

p4b_g2_seed_42_results = run(
    treatment="focal",
    gamma=2.0,
    seed=42,
    output_root=P4B_GAMMA2_OUTPUT_LOCATION,
)

p4b_g2_seed_0_results = run(
    treatment="focal",
    gamma=2.0,
    seed=0,
    output_root=P4B_GAMMA2_OUTPUT_LOCATION,
)

p4b_g2_seed_1_results = run(
    treatment="focal",
    gamma=2.0,
    seed=1,
    output_root=P4B_GAMMA2_OUTPUT_LOCATION,
)

======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: focal
Seed: 42
Run name: phase4_focal_g2_seed42_20260619_134728
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g2_seed42_20260619_134728
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

No back-translation applied to treatment 'focal'.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 414.2 seconds (6.90 minutes).
Peak training GPU memory: 3.19 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.7004618429733891,
  "macro_f1": 0.6429882862291191,
  "weighted_f1": 0.6997865160045743,
  "per_class_f1": [
    0.5011135857461024,
    0.5641025641025641,
    0.7014925373134329,
    0.8132069703454601,
    0.6375545851528385,
    0.6002290950744559,
    0.68321866586898
  ],
  "report": {
    "anger": {
      "precision": 0.5447941888619855,
      "recall": 0.4639175257731959,
      "f1-score": 0.5011135857461024,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.5892857142857143,
      "recall": 0.5409836065573771,
      "f1-score": 0.5641025641025641,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6911764705882353,
      "recall": 0.7121212121212122,
      "f1-score": 0.7014925373134329,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8296943231441049,
      "recall": 0.7973621103117506,
      "f1-score": 0.8132069703454601,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.6728110599078341,
      "recall": 0.6058091286307054,
      "f1-score": 0.6375545851528385,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5981735159817352,
      "recall": 0.6022988505747127,
      "f1-score": 0.6002290950744559,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6518264840182648,
      "recall": 0.7177875549968573,
      "f1-score": 0.68321866586898,
      "support": 1591.0
    },
    "accuracy": 0.7004618429733891,
    "macro avg": {
      "precision": 0.6539659652554105,
      "recall": 0.6343257127094015,
      "f1-score": 0.6429882862291191,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.7013697535068362,
      "recall": 0.7004618429733891,
      "f1-score": 0.6997865160045743,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6954248366013072,
  "macro_f1": 0.631515034959964,
  "weighted_f1": 0.6940874646516955,
  "per_class_f1": [
    0.5157232704402516,
    0.5217391304347826,
    0.6956521739130435,
    0.8137843819159026,
    0.6118143459915611,
    0.5748373101952278,
    0.6870546318289786
  ],
  "report": {
    "anger": {
      "precision": 0.5668202764976958,
      "recall": 0.47307692307692306,
      "f1-score": 0.5157232704402516,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.5806451612903226,
      "recall": 0.47368421052631576,
      "f1-score": 0.5217391304347826,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6666666666666666,
      "recall": 0.7272727272727273,
      "f1-score": 0.6956521739130435,
      "support": 77.0
    },
    "joy": {
      "precision": 0.825,
      "recall": 0.8028696194635059,
      "f1-score": 0.8137843819159026,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.6744186046511628,
      "recall": 0.5598455598455598,
      "f1-score": 0.6118143459915611,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5602536997885835,
      "recall": 0.5902004454342984,
      "f1-score": 0.5748373101952278,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6566401816118048,
      "recall": 0.7204234122042341,
      "f1-score": 0.6870546318289786,
      "support": 1606.0
    },
    "accuracy": 0.6954248366013072,
    "macro avg": {
      "precision": 0.6472063700723194,
      "recall": 0.6210532711176521,
      "f1-score": 0.631515034959964,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6957464860236348,
      "recall": 0.6954248366013072,
      "f1-score": 0.6940874646516955,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g2_seed42_20260619_134728/checkpoints/checkpoint-2270

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g2_seed42_20260619_134728

No original dataset files were modified.
======================================================================
======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: focal
Seed: 0
Run name: phase4_focal_g2_seed0_20260619_135442
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g2_seed0_20260619_135442
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

No back-translation applied to treatment 'focal'.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 401.3 seconds (6.69 minutes).
Peak training GPU memory: 3.19 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.7009016934242358,
  "macro_f1": 0.6414544630559132,
  "weighted_f1": 0.6989100896036408,
  "per_class_f1": [
    0.5202558635394456,
    0.528,
    0.7338129496402878,
    0.8148591971240263,
    0.6529680365296804,
    0.5578406169665809,
    0.6824445775913721
  ],
  "report": {
    "anger": {
      "precision": 0.5386313465783664,
      "recall": 0.5030927835051546,
      "f1-score": 0.5202558635394456,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.515625,
      "recall": 0.5409836065573771,
      "f1-score": 0.528,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6986301369863014,
      "recall": 0.7727272727272727,
      "f1-score": 0.7338129496402878,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8143712574850299,
      "recall": 0.815347721822542,
      "f1-score": 0.8148591971240263,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.7258883248730964,
      "recall": 0.5933609958506224,
      "f1-score": 0.6529680365296804,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.6326530612244898,
      "recall": 0.49885057471264366,
      "f1-score": 0.5578406169665809,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6519748139668002,
      "recall": 0.715901948460088,
      "f1-score": 0.6824445775913721,
      "support": 1591.0
    },
    "accuracy": 0.7009016934242358,
    "macro avg": {
      "precision": 0.6539677058734406,
      "recall": 0.6343235576622429,
      "f1-score": 0.6414544630559132,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.7003750322333148,
      "recall": 0.7009016934242358,
      "f1-score": 0.6989100896036408,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6915032679738562,
  "macro_f1": 0.6261876984019441,
  "weighted_f1": 0.6879654719732325,
  "per_class_f1": [
    0.5168539325842697,
    0.5314685314685315,
    0.6885245901639344,
    0.8118628359592215,
    0.6140350877192983,
    0.540272614622057,
    0.6802962962962963
  ],
  "report": {
    "anger": {
      "precision": 0.55119825708061,
      "recall": 0.48653846153846153,
      "f1-score": 0.5168539325842697,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.5671641791044776,
      "recall": 0.5,
      "f1-score": 0.5314685314685315,
      "support": 76.0
    },
    "fear": {
      "precision": 0.5943396226415094,
      "recall": 0.8181818181818182,
      "f1-score": 0.6885245901639344,
      "support": 77.0
    },
    "joy": {
      "precision": 0.8041615667074663,
      "recall": 0.8197130380536494,
      "f1-score": 0.8118628359592215,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.7106598984771574,
      "recall": 0.5405405405405406,
      "f1-score": 0.6140350877192983,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.6089385474860335,
      "recall": 0.48552338530066813,
      "f1-score": 0.540272614622057,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6489542114188808,
      "recall": 0.7148194271481942,
      "f1-score": 0.6802962962962963,
      "support": 1606.0
    },
    "accuracy": 0.6915032679738562,
    "macro avg": {
      "precision": 0.640773754702305,
      "recall": 0.6236166672519046,
      "f1-score": 0.6261876984019441,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6893807186786182,
      "recall": 0.6915032679738562,
      "f1-score": 0.6879654719732325,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g2_seed0_20260619_135442/checkpoints/checkpoint-2270

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g2_seed0_20260619_135442

No original dataset files were modified.
======================================================================
======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: focal
Seed: 1
Run name: phase4_focal_g2_seed1_20260619_140142
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g2_seed1_20260619_140142
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

No back-translation applied to treatment 'focal'.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 399.5 seconds (6.66 minutes).
Peak training GPU memory: 3.19 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.7004618429733891,
  "macro_f1": 0.6341205453661475,
  "weighted_f1": 0.6999801631165703,
  "per_class_f1": [
    0.5501022494887525,
    0.5196850393700787,
    0.6511627906976745,
    0.8186650915534555,
    0.6328600405679513,
    0.5981941309255079,
    0.6681744749596122
  ],
  "report": {
    "anger": {
      "precision": 0.5456389452332657,
      "recall": 0.554639175257732,
      "f1-score": 0.5501022494887525,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.5,
      "recall": 0.5409836065573771,
      "f1-score": 0.5196850393700787,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6666666666666666,
      "recall": 0.6363636363636364,
      "f1-score": 0.6511627906976745,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8067520372526193,
      "recall": 0.8309352517985612,
      "f1-score": 0.8186650915534555,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.6190476190476191,
      "recall": 0.6473029045643154,
      "f1-score": 0.6328600405679513,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5875831485587583,
      "recall": 0.6091954022988506,
      "f1-score": 0.5981941309255079,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6875,
      "recall": 0.6499057196731616,
      "f1-score": 0.6681744749596122,
      "support": 1591.0
    },
    "accuracy": 0.7004618429733891,
    "macro avg": {
      "precision": 0.6304554881084183,
      "recall": 0.6384750995019477,
      "f1-score": 0.6341205453661475,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.7001097278181304,
      "recall": 0.7004618429733891,
      "f1-score": 0.6999801631165703,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6925925925925925,
  "macro_f1": 0.6360978566751975,
  "weighted_f1": 0.6914008229181837,
  "per_class_f1": [
    0.5280788177339901,
    0.5033112582781457,
    0.725,
    0.8146564885496184,
    0.6196078431372549,
    0.5949367088607594,
    0.6670938801666133
  ],
  "report": {
    "anger": {
      "precision": 0.5414141414141415,
      "recall": 0.5153846153846153,
      "f1-score": 0.5280788177339901,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.5066666666666667,
      "recall": 0.5,
      "f1-score": 0.5033112582781457,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6987951807228916,
      "recall": 0.7532467532467533,
      "f1-score": 0.725,
      "support": 77.0
    },
    "joy": {
      "precision": 0.7978468899521531,
      "recall": 0.8321896444167186,
      "f1-score": 0.8146564885496184,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.6294820717131474,
      "recall": 0.61003861003861,
      "f1-score": 0.6196078431372549,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5651302605210421,
      "recall": 0.6280623608017817,
      "f1-score": 0.5949367088607594,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6871287128712872,
      "recall": 0.6481942714819428,
      "f1-score": 0.6670938801666133,
      "support": 1606.0
    },
    "accuracy": 0.6925925925925925,
    "macro avg": {
      "precision": 0.6323519891230471,
      "recall": 0.6410166079100603,
      "f1-score": 0.6360978566751975,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6913084684378921,
      "recall": 0.6925925925925925,
      "f1-score": 0.6914008229181837,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g2_seed1_20260619_140142/checkpoints/checkpoint-3405

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g2_seed1_20260619_140142

No original dataset files were modified.
======================================================================

In [ ]:
P4B_GAMMA1_OUTPUT_LOCATION = (
        "/content/drive/MyDrive/Thesis/models_new"
)

p4b_g1_seed_42_results = run(
    treatment="focal",
    gamma=1.0,
    seed=42,
    output_root=P4B_GAMMA1_OUTPUT_LOCATION,
)

p4b_g1_seed_0_results = run(
    treatment="focal",
    gamma=1.0,
    seed=0,
    output_root=P4B_GAMMA1_OUTPUT_LOCATION,
)

p4b_g1_seed_1_results = run(
    treatment="focal",
    gamma=1.0,
    seed=1,
    output_root=P4B_GAMMA1_OUTPUT_LOCATION,
)

======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: focal
Seed: 42
Run name: phase4_focal_g1_seed42_20260619_140902
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g1_seed42_20260619_140902
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

No back-translation applied to treatment 'focal'.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 396.2 seconds (6.60 minutes).
Peak training GPU memory: 3.19 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.7035407961293161,
  "macro_f1": 0.6459262373500668,
  "weighted_f1": 0.7030719010691867,
  "per_class_f1": [
    0.5505735140771637,
    0.5470085470085471,
    0.7014925373134329,
    0.8182897862232779,
    0.6317907444668008,
    0.5979843225083986,
    0.674344209852847
  ],
  "report": {
    "anger": {
      "precision": 0.5569620253164557,
      "recall": 0.5443298969072164,
      "f1-score": 0.5505735140771637,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.5714285714285714,
      "recall": 0.5245901639344263,
      "f1-score": 0.5470085470085471,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6911764705882353,
      "recall": 0.7121212121212122,
      "f1-score": 0.7014925373134329,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8105882352941176,
      "recall": 0.8261390887290168,
      "f1-score": 0.8182897862232779,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.61328125,
      "recall": 0.6514522821576764,
      "f1-score": 0.6317907444668008,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5829694323144105,
      "recall": 0.6137931034482759,
      "f1-score": 0.5979843225083986,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6866449511400652,
      "recall": 0.6624764299182904,
      "f1-score": 0.674344209852847,
      "support": 1591.0
    },
    "accuracy": 0.7035407961293161,
    "macro avg": {
      "precision": 0.644721562297408,
      "recall": 0.6478431681737307,
      "f1-score": 0.6459262373500668,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.7029925555829443,
      "recall": 0.7035407961293161,
      "f1-score": 0.7030719010691867,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.690631808278867,
  "macro_f1": 0.6333720929036869,
  "weighted_f1": 0.6894297120026218,
  "per_class_f1": [
    0.5288932419196866,
    0.5179856115107914,
    0.7195121951219512,
    0.8140672782874617,
    0.6007905138339921,
    0.5852631578947368,
    0.6670926517571885
  ],
  "report": {
    "anger": {
      "precision": 0.5389221556886228,
      "recall": 0.5192307692307693,
      "f1-score": 0.5288932419196866,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.5714285714285714,
      "recall": 0.47368421052631576,
      "f1-score": 0.5179856115107914,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6781609195402298,
      "recall": 0.7662337662337663,
      "f1-score": 0.7195121951219512,
      "support": 77.0
    },
    "joy": {
      "precision": 0.7984403119376124,
      "recall": 0.8303181534622582,
      "f1-score": 0.8140672782874617,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.6153846153846154,
      "recall": 0.5868725868725869,
      "f1-score": 0.6007905138339921,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.5548902195608783,
      "recall": 0.6191536748329621,
      "f1-score": 0.5852631578947368,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6850393700787402,
      "recall": 0.6500622665006227,
      "f1-score": 0.6670926517571885,
      "support": 1606.0
    },
    "accuracy": 0.690631808278867,
    "macro avg": {
      "precision": 0.63460945194561,
      "recall": 0.6350793468084689,
      "f1-score": 0.6333720929036869,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6894313410765037,
      "recall": 0.690631808278867,
      "f1-score": 0.6894297120026218,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g1_seed42_20260619_140902/checkpoints/checkpoint-3405

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g1_seed42_20260619_140902

No original dataset files were modified.
======================================================================
======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: focal
Seed: 0
Run name: phase4_focal_g1_seed0_20260619_141557
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g1_seed0_20260619_141557
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

No back-translation applied to treatment 'focal'.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 402.1 seconds (6.70 minutes).
Peak training GPU memory: 3.19 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.7004618429733891,
  "macro_f1": 0.6425316373105493,
  "weighted_f1": 0.6987002692725582,
  "per_class_f1": [
    0.5202558635394456,
    0.544,
    0.7194244604316546,
    0.8143283582089552,
    0.6484018264840182,
    0.5721455457967378,
    0.6791654067130329
  ],
  "report": {
    "anger": {
      "precision": 0.5386313465783664,
      "recall": 0.5030927835051546,
      "f1-score": 0.5202558635394456,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.53125,
      "recall": 0.5573770491803278,
      "f1-score": 0.544,
      "support": 61.0
    },
    "fear": {
      "precision": 0.684931506849315,
      "recall": 0.7575757575757576,
      "f1-score": 0.7194244604316546,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8109393579072532,
      "recall": 0.8177458033573142,
      "f1-score": 0.8143283582089552,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.7208121827411168,
      "recall": 0.5892116182572614,
      "f1-score": 0.6484018264840182,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.6298342541436464,
      "recall": 0.5241379310344828,
      "f1-score": 0.5721455457967378,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6544289044289044,
      "recall": 0.7058453802639849,
      "f1-score": 0.6791654067130329,
      "support": 1591.0
    },
    "accuracy": 0.7004618429733891,
    "macro avg": {
      "precision": 0.6529753646640861,
      "recall": 0.6364266175963262,
      "f1-score": 0.6425316373105493,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.6994468451883314,
      "recall": 0.7004618429733891,
      "f1-score": 0.6987002692725582,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.6930283224400872,
  "macro_f1": 0.6259526084659065,
  "weighted_f1": 0.6897490508094501,
  "per_class_f1": [
    0.5207700101317123,
    0.527027027027027,
    0.6741573033707865,
    0.8128834355828221,
    0.612691466083151,
    0.5536585365853659,
    0.6804804804804805
  ],
  "report": {
    "anger": {
      "precision": 0.550321199143469,
      "recall": 0.49423076923076925,
      "f1-score": 0.5207700101317123,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.5416666666666666,
      "recall": 0.5131578947368421,
      "f1-score": 0.527027027027027,
      "support": 76.0
    },
    "fear": {
      "precision": 0.594059405940594,
      "recall": 0.7792207792207793,
      "f1-score": 0.6741573033707865,
      "support": 77.0
    },
    "joy": {
      "precision": 0.79963789981895,
      "recall": 0.8265751715533375,
      "f1-score": 0.8128834355828221,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.7070707070707071,
      "recall": 0.5405405405405406,
      "f1-score": 0.612691466083151,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.6118598382749326,
      "recall": 0.5055679287305123,
      "f1-score": 0.5536585365853659,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6571925754060325,
      "recall": 0.7054794520547946,
      "f1-score": 0.6804804804804805,
      "support": 1606.0
    },
    "accuracy": 0.6930283224400872,
    "macro avg": {
      "precision": 0.637401184617336,
      "recall": 0.6235389337239393,
      "f1-score": 0.6259526084659065,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6902404083893942,
      "recall": 0.6930283224400872,
      "f1-score": 0.6897490508094501,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g1_seed0_20260619_141557/checkpoints/checkpoint-2270

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g1_seed0_20260619_141557

No original dataset files were modified.
======================================================================
======================================================================
PHASE 4 EXPERIMENT
======================================================================
Treatment: focal
Seed: 1
Run name: phase4_focal_g1_seed1_20260619_142259
All new results will be saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g1_seed1_20260619_142259
======================================================================

Original dataset sizes:
Training:   36,302
Validation: 4,547
Test:       4,590

No back-translation applied to treatment 'focal'.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed in 409.5 seconds (6.82 minutes).
Peak training GPU memory: 3.19 GB

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating validation set...

Evaluating test set...

======================================================================
FINAL RESULTS
======================================================================

Validation metrics:
{
  "accuracy": 0.7000219925225424,
  "macro_f1": 0.6345630010451043,
  "weighted_f1": 0.6997620638590203,
  "per_class_f1": [
    0.541033434650456,
    0.532258064516129,
    0.6412213740458015,
    0.8168097070139094,
    0.6421267893660532,
    0.5975197294250282,
    0.6709719082983533
  ],
  "report": {
    "anger": {
      "precision": 0.5318725099601593,
      "recall": 0.5505154639175258,
      "f1-score": 0.541033434650456,
      "support": 485.0
    },
    "disgust": {
      "precision": 0.5238095238095238,
      "recall": 0.5409836065573771,
      "f1-score": 0.532258064516129,
      "support": 61.0
    },
    "fear": {
      "precision": 0.6461538461538462,
      "recall": 0.6363636363636364,
      "f1-score": 0.6412213740458015,
      "support": 66.0
    },
    "joy": {
      "precision": 0.8065458796025716,
      "recall": 0.8273381294964028,
      "f1-score": 0.8168097070139094,
      "support": 1668.0
    },
    "sadness": {
      "precision": 0.6330645161290323,
      "recall": 0.6514522821576764,
      "f1-score": 0.6421267893660532,
      "support": 241.0
    },
    "surprise": {
      "precision": 0.5862831858407079,
      "recall": 0.6091954022988506,
      "f1-score": 0.5975197294250282,
      "support": 435.0
    },
    "neutral": {
      "precision": 0.6899070385126163,
      "recall": 0.6530483972344437,
      "f1-score": 0.6709719082983533,
      "support": 1591.0
    },
    "accuracy": 0.7000219925225424,
    "macro avg": {
      "precision": 0.6310909285726367,
      "recall": 0.6384138454322732,
      "f1-score": 0.6345630010451043,
      "support": 4547.0
    },
    "weighted avg": {
      "precision": 0.7000481772174354,
      "recall": 0.7000219925225424,
      "f1-score": 0.6997620638590203,
      "support": 4547.0
    }
  }
}

Test metrics:
{
  "accuracy": 0.69520697167756,
  "macro_f1": 0.6373156997669047,
  "weighted_f1": 0.6941145089158449,
  "per_class_f1": [
    0.537109375,
    0.5165562913907285,
    0.7125,
    0.8172108635947513,
    0.6111111111111112,
    0.5964172813487882,
    0.6703049759229535
  ],
  "report": {
    "anger": {
      "precision": 0.5456349206349206,
      "recall": 0.5288461538461539,
      "f1-score": 0.537109375,
      "support": 520.0
    },
    "disgust": {
      "precision": 0.52,
      "recall": 0.5131578947368421,
      "f1-score": 0.5165562913907285,
      "support": 76.0
    },
    "fear": {
      "precision": 0.6867469879518072,
      "recall": 0.7402597402597403,
      "f1-score": 0.7125,
      "support": 77.0
    },
    "joy": {
      "precision": 0.7998805256869773,
      "recall": 0.835308796007486,
      "f1-score": 0.8172108635947513,
      "support": 1603.0
    },
    "sadness": {
      "precision": 0.6285714285714286,
      "recall": 0.5945945945945946,
      "f1-score": 0.6111111111111112,
      "support": 259.0
    },
    "surprise": {
      "precision": 0.566,
      "recall": 0.6302895322939867,
      "f1-score": 0.5964172813487882,
      "support": 449.0
    },
    "neutral": {
      "precision": 0.6918489065606361,
      "recall": 0.6500622665006227,
      "f1-score": 0.6703049759229535,
      "support": 1606.0
    },
    "accuracy": 0.69520697167756,
    "macro avg": {
      "precision": 0.6340975384865385,
      "recall": 0.6417884254627753,
      "f1-score": 0.6373156997669047,
      "support": 4590.0
    },
    "weighted avg": {
      "precision": 0.6942007632712536,
      "recall": 0.69520697167756,
      "f1-score": 0.6941145089158449,
      "support": 4590.0
    }
  }
}

Best checkpoint:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g1_seed1_20260619_142259/checkpoints/checkpoint-3405

All results were saved in:
/content/drive/MyDrive/Thesis/models_new/phase4_focal_g1_seed1_20260619_142259

No original dataset files were modified.
======================================================================